<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/ex_pandas1_solucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab: Seleção de Dados em Pandas

---

## **CASE Insurance**

Acesse a base de dados [`insurance`](https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/insurance.csv) para as questões a seguir.

##### Q1. Acesse os dados explore a estrutura básica dos dados de `insurance`.

> * Qual o número de caso de seguro?
> * Quantos atributos são numéricos?
> * Há quantos valores diferentes para região?
> * Qual a maior quantidade de filhos?

In [3]:
import pandas as pd

df = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/insurance.csv')

##### Explore a estrutura básica dos dados de insurance.

In [4]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [6]:
df.shape, df.shape[0], len(df)

((1338, 7), 1338, 1338)

In [7]:
df.describe(include='all')

,age,sex,bmi,children,smoker,region,charges
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN
mean,39.207025,NaN,30.663397,1.094918,NaN,NaN,13270.422265
std,14.049960,NaN,6.098187,1.205493,NaN,NaN,12110.011237
min,18.000000,NaN,15.960000,0.000000,NaN,NaN,1121.873900
25%,27.000000,NaN,26.296250,0.000000,NaN,NaN,4740.287150
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.033000
75%,51.000000,NaN,34.693750,2.000000,NaN,NaN,16639.912515
max,64.000000,NaN,53.130000,5.000000,NaN,NaN,63770.428010

#### Perguntas

> * Qual o número de caso de seguro?
> * Quantos atributos são numéricos?
> * Há quantos valores diferentes para região?
> * Qual a maior quantidade de filhos?

In [8]:
len(df)

1338

In [9]:
print(f'Número de casos de seguro: {len(df)}')

Número de casos de seguro: 1338

In [10]:
print(f'Custo médio dos seguros: {df.charges.mean():.2f}')

Custo médio dos seguros: 13270.42

In [11]:
df.dtypes, df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

(age           int64
 sex          object
 bmi         float64
 children      int64
 smoker       object
 region       object
 charges     float64
 dtype: object,
 None)

In [12]:
df.columns, len(df.columns)

(Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object'),
 7)

In [13]:
df[ df.columns[2:5] ]

         bmi  children smoker
0     27.900         0    yes
1     33.770         1     no
2     33.000         3     no
3     22.705         0     no
4     28.880         0     no
...      ...       ...    ...
1333  30.970         3     no
1334  31.920         0     no
1335  36.850         0     no
1336  25.800         0     no
1337  29.070         0    yes

[1338 rows x 3 columns]

In [14]:
df.select_dtypes(include=['number']).columns

Index(['age', 'bmi', 'children', 'charges'], dtype='object')

In [ ]:
df.region.value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [ ]:
df.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
len(df.region.unique())

4

In [ ]:
df.region.nunique()

4

In [ ]:
for r in df.region.unique():
  print(f'{r}: {len(df[df.region == r])}')

southwest: 325
southeast: 364
northwest: 325
northeast: 324

In [ ]:
df.children.max()

5

In [ ]:
df.children.nlargest(1)

32    5
Name: children, dtype: int64

In [ ]:
df.sort_values(by='children', ascending=False)

      age     sex     bmi  children smoker     region      charges
1245   28    male  24.300         5     no  southwest   5615.36900
877    33    male  33.440         5     no  southeast   6653.78860
71     31    male  28.500         5     no  northeast   6799.45800
1272   43    male  25.520         5     no  southeast  14478.33015
568    49  female  31.900         5     no  southwest  11552.90400
...   ...     ...     ...       ...    ...        ...          ...
757    47  female  27.830         0    yes  southeast  23065.42070
1331   23  female  33.400         0     no  southwest  10795.93733
1326   42  female  32.870         0     no  northeast   7050.02130
1325   61    male  33.535         0     no  northeast  13143.33665
1322   62    male  38.830         0     no  southeast  12981.34570

[1338 rows x 7 columns]

##### Q2. Qual a quantidade de casos por região?

In [ ]:
df.region.value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

##### Q3. Qual a média dos pagamentos (charges) efetuados?

In [ ]:
df.charges.mean()

np.float64(13270.422265141257)

##### Q4. Qual a média dos pagamentos (charges) dos 10 maiores pagamentos efetuados?

In [ ]:
df.charges.nlargest(10).mean()

np.float64(55130.961078)

In [ ]:
df.charges.nlargest(10)

543     63770.42801
1300    62592.87309
1230    60021.39897
577     58571.07448
819     55135.40209
1146    52590.82939
34      51194.55914
1241    49577.66240
1062    48970.24760
488     48885.13561
Name: charges, dtype: float64

In [15]:
df.nlargest(10, 'charges')

      age     sex     bmi  children smoker     region      charges
543    54  female  47.410         0    yes  southeast  63770.42801
1300   45    male  30.360         0    yes  southeast  62592.87309
1230   52    male  34.485         3    yes  northwest  60021.39897
577    31  female  38.095         1    yes  northeast  58571.07448
819    33  female  35.530         0    yes  northwest  55135.40209
1146   60    male  32.800         0    yes  southwest  52590.82939
34     28    male  36.400         1    yes  southwest  51194.55914
1241   64    male  36.960         2    yes  southeast  49577.66240
1062   59    male  41.140         1    yes  southeast  48970.24760
488    44  female  38.060         0    yes  southeast  48885.13561

In [16]:
df.nlargest(10, 'charges').children.mean()

np.float64(0.8)

##### Q5. Calcule a distância interquartis dos pagamentos.

**Dica** Empregue a função `quantile()` do `Pandas` e use IQR = Q3 - Q1.

In [ ]:
inf = df.charges.quantile(0.25)
sup = df.charges.quantile(0.75)
iqr = sup - inf

[ inf -  1.5*iqr, sup + 1.5*iqr ]

[np.float64(-13109.1508975), np.float64(34489.350562499996)]

##### Q6. Empregue o valor IQR da questão anterior para verificar se existem *outliers* dos pagamentos.

**Dica** *outliers* são dados fora do intervalo $[Q1 - 1.5 IQR, Q3 + 1.5 IQR]$

In [ ]:
df[ df.charges > sup + 1.5*iqr ]

      age     sex     bmi  children smoker     region      charges
14     27    male  42.130         0    yes  southeast  39611.75770
19     30    male  35.300         0    yes  southwest  36837.46700
23     34  female  31.920         1    yes  northeast  37701.87680
29     31    male  36.300         2    yes  southwest  38711.00000
30     22    male  35.600         0    yes  southwest  35585.57600
...   ...     ...     ...       ...    ...        ...          ...
1300   45    male  30.360         0    yes  southeast  62592.87309
1301   62    male  30.875         3    yes  northwest  46718.16325
1303   43    male  27.800         0    yes  southwest  37829.72420
1313   19  female  34.700         2    yes  southwest  36397.57600
1323   42  female  40.370         2    yes  southeast  43896.37630

[139 rows x 7 columns]

In [ ]:
df[ df.charges < inf - 1.5*iqr ]

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

##### Q7. Qual a média dos pagamentos efetuados para os 10 casos com menor idade dos segurados? Aqui, empregue a função `nsmallest()`.

In [ ]:
df.nsmallest(10, 'age').charges.mean()

np.float64(11968.65424)

##### Q8. Revise a questão anterior. De fato calculamos a média de *todos* os seguros de indivíduos com idade entre as 10 menores idades?

**Dica** Verifique quantos indivíduos há com a menor idade

In [ ]:
df.age.value_counts()

age
18    69
19    68
46    29
52    29
50    29
47    29
48    29
51    29
45    29
20    29
24    28
27    28
28    28
25    28
23    28
49    28
54    28
53    28
22    28
21    28
26    28
31    27
41    27
44    27
43    27
42    27
29    27
30    27
40    27
32    26
33    26
57    26
34    26
55    26
56    26
35    25
58    25
37    25
59    25
39    25
36    25
38    25
62    23
60    23
63    23
61    23
64    22
Name: count, dtype: int64

In [ ]:
df[ df.age == df.age.min() ].charges.mean()

np.float64(7086.217556362319)