<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Exemplo_CigarettesSW_selecao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/CigarettesSW.csv")
df = df.drop(columns="rownames")
df.head()

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335
1,AR,1985,1.076,2327000,128.534592,26210736,37.000000,101.474998,37.000000
2,AZ,1985,1.076,3184000,104.522614,43956936,31.000000,108.578751,36.170418
3,CA,1985,1.076,26444000,100.363037,447102816,26.000000,107.837341,32.104000
4,CO,1985,1.076,3209000,112.963539,49466672,31.000000,94.266663,31.000000

# Explorando a estrutura

In [3]:
df.shape

(96, 9)

In [4]:
len(df)

96

In [5]:
df.columns

Index(['state', 'year', 'cpi', 'population', 'packs', 'income', 'tax', 'price',
       'taxs'],
      dtype='object')

In [6]:
df.describe(include='all')

,state,year,cpi,population,packs,income,tax,price,taxs
count,96,96.000000,96.000000,9.600000e+01,96.000000,9.600000e+01,96.000000,96.000000,96.000000
unique,48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,AL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1990.000000,1.300000,5.168866e+06,109.182424,9.987874e+07,42.684028,143.447938,48.326150
std,NaN,5.026247,0.225176,5.442345e+06,25.871305,1.205411e+08,16.138088,43.887444,19.332215
min,NaN,1985.000000,1.076000,4.784470e+05,49.272198,6.887097e+06,18.000000,84.967995,21.268000
25%,NaN,1985.000000,1.076000,1.622606e+06,92.450159,2.552038e+07,31.000000,102.706415,34.770125
50%,NaN,1990.000000,1.300000,3.697472e+06,110.160660,6.166164e+07,37.000002,137.720383,41.048750
75%,NaN,1995.000000,1.524000,5.901500e+06,123.523010,1.273140e+08,50.875000,176.150471,59.476979
max,NaN,1995.000000,1.524000,3.149352e+07,197.993988,7.714701e+08,99.000000,240.849670,112.633003

In [7]:
df.dtypes

state          object
year            int64
cpi           float64
population      int64
packs         float64
income          int64
tax           float64
price         float64
taxs          float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   state       96 non-null     object
 1   year        96 non-null     int64
 2   cpi         96 non-null     float64
 3   population  96 non-null     int64
 4   packs       96 non-null     float64
 5   income      96 non-null     int64
 6   tax         96 non-null     float64
 7   price       96 non-null     float64
 8   taxs        96 non-null     float64
dtypes: float64(5), int64(3), object(1)
memory usage: 6.9+ KB

# Automatic EDA

Opções: Sweetviz, Autoviz, YData Profiling (antigo Pandas Profiling)

In [9]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.0.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 7.1 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 5.6 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 18.6 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 10.2 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 4.0 MB/s eta 0:00:00
Downloading puremagic-2.0.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 2.1 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.0.2 visions-0.8.1 ydata-profiling-4.18.1

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="EDA do DataFrame df")
profile.to_notebook_iframe()

## Seleção de Colunas, Seleção de Linhas e de Linhas e Colunas

<img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg" width=320, align="center">

## Seleção de 1 Coluna

In [11]:
df.head()

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335
1,AR,1985,1.076,2327000,128.534592,26210736,37.000000,101.474998,37.000000
2,AZ,1985,1.076,3184000,104.522614,43956936,31.000000,108.578751,36.170418
3,CA,1985,1.076,26444000,100.363037,447102816,26.000000,107.837341,32.104000
4,CO,1985,1.076,3209000,112.963539,49466672,31.000000,94.266663,31.000000

In [12]:
df['price']

0     102.181671
1     101.474998
2     108.578751
3     107.837341
4      94.266663
         ...
91    175.638748
92    239.109344
93    201.381256
94    166.517181
95    158.541656
Name: price, Length: 96, dtype: float64

In [13]:
df.price

0     102.181671
1     101.474998
2     108.578751
3     107.837341
4      94.266663
         ...
91    175.638748
92    239.109344
93    201.381256
94    166.517181
95    158.541656
Name: price, Length: 96, dtype: float64

In [15]:
type(df.price), type(df)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [16]:
df['price'], df.price

(0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
 0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64)

In [19]:
selecao = 'price'

df['price'], df.price, df[selecao]

(0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
 0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
 0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64)

In [22]:
df.price.mean(), df['price'].sum(), df['price'].var(), df.price.quantile(0.10)

(np.float64(143.44793836275736),
 np.float64(13771.002082824707),
 1926.1077506168351,
 np.float64(97.02925109863281))

In [23]:
df.price / df.price.max()

0     0.424255
1     0.421321
2     0.450815
3     0.447737
4     0.391392
        ...
91    0.729246
92    0.992774
93    0.836128
94    0.691374
95    0.658260
Name: price, Length: 96, dtype: float64

## Cuidado: Series x DataFrame

In [26]:
df['price'], df.price, df[['price']]

(0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
 0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
          price
 0   102.181671
 1   101.474998
 2   108.578751
 3   107.837341
 4    94.266663
 ..         ...
 91  175.638748
 92  239.109344
 93  201.381256
 94  166.517181
 95  158.541656

 [96 rows x 1 columns])

In [29]:
df['price'], df[['price']]

(0     102.181671
 1     101.474998
 2     108.578751
 3     107.837341
 4      94.266663
          ...
 91    175.638748
 92    239.109344
 93    201.381256
 94    166.517181
 95    158.541656
 Name: price, Length: 96, dtype: float64,
          price
 0   102.181671
 1   101.474998
 2   108.578751
 3   107.837341
 4    94.266663
 ..         ...
 91  175.638748
 92  239.109344
 93  201.381256
 94  166.517181
 95  158.541656

 [96 rows x 1 columns])

In [30]:
df['price'].mean(), df[['price']].mean()

(np.float64(143.44793836275736),
 price    143.447938
 dtype: float64)

In [31]:
df[['price']].columns

Index(['price'], dtype='object')

In [33]:
%%script echo off
df['price'].columns

off

In [35]:
df['price'].nlargest(5)

67    240.849670
92    239.109344
84    224.459244
79    221.858002
68    220.348663
Name: price, dtype: float64

In [38]:
df.state.value_counts()

state
AL    2
AR    2
AZ    2
CA    2
CO    2
CT    2
DE    2
FL    2
GA    2
IA    2
ID    2
IL    2
IN    2
KS    2
KY    2
LA    2
MA    2
MD    2
ME    2
MI    2
MN    2
MO    2
MS    2
MT    2
NC    2
ND    2
NE    2
NH    2
NJ    2
NM    2
NV    2
NY    2
OH    2
OK    2
OR    2
PA    2
RI    2
SC    2
SD    2
TN    2
TX    2
UT    2
VA    2
VT    2
WA    2
WI    2
WV    2
WY    2
Name: count, dtype: int64

In [41]:
tips = pd.read_csv('https://raw.githubusercontent.com/Rogerio-mack/Visualizacao-de-Dados-em-Python/main/data/tips.csv')
tips.head()

tips.sex.value_counts(), tips['day'].value_counts()

(sex
 Male      157
 Female     87
 Name: count, dtype: int64,
 day
 Sat     87
 Sun     76
 Thur    62
 Fri     19
 Name: count, dtype: int64)

## Seleção de $n$ colunas

In [43]:
df.head()

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335
1,AR,1985,1.076,2327000,128.534592,26210736,37.000000,101.474998,37.000000
2,AZ,1985,1.076,3184000,104.522614,43956936,31.000000,108.578751,36.170418
3,CA,1985,1.076,26444000,100.363037,447102816,26.000000,107.837341,32.104000
4,CO,1985,1.076,3209000,112.963539,49466672,31.000000,94.266663,31.000000

In [45]:
df[ ['state','price'] ]

   state       price
0     AL  102.181671
1     AR  101.474998
2     AZ  108.578751
3     CA  107.837341
4     CO   94.266663
..   ...         ...
91    VT  175.638748
92    WA  239.109344
93    WI  201.381256
94    WV  166.517181
95    WY  158.541656

[96 rows x 2 columns]

In [46]:
df[ ['state','income', 'price'] ]

   state     income       price
0     AL   46014968  102.181671
1     AR   26210736  101.474998
2     AZ   43956936  108.578751
3     CA  447102816  107.837341
4     CO   49466672   94.266663
..   ...        ...         ...
91    VT   12448607  175.638748
92    WA  129680832  239.109344
93    WI  115959680  201.381256
94    WV   32611268  166.517181
95    WY   10293195  158.541656

[96 rows x 3 columns]

In [48]:
df[ ['income', 'price'] ].mean()

income    9.987874e+07
price     1.434479e+02
dtype: float64

In [49]:
selecao = ['income', 'price']

df[ selecao ].mean()

income    9.987874e+07
price     1.434479e+02
dtype: float64

## Seleção de Linhas

In [50]:
df.head()

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335
1,AR,1985,1.076,2327000,128.534592,26210736,37.000000,101.474998,37.000000
2,AZ,1985,1.076,3184000,104.522614,43956936,31.000000,108.578751,36.170418
3,CA,1985,1.076,26444000,100.363037,447102816,26.000000,107.837341,32.104000
4,CO,1985,1.076,3209000,112.963539,49466672,31.000000,94.266663,31.000000

In [51]:
df[ df.state == 'AL' ]

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335
48,AL,1995,1.524,4262731,101.085434,83903280,40.500004,158.371338,41.904671

In [54]:
df[ df.price < 90 ]

,state,year,cpi,population,packs,income,tax,price,taxs
14,KY,1985,1.076,3695000,186.035187,42703144,19.0,87.001251,23.142918
24,NC,1985,1.076,6255000,155.283768,79104656,18.0,84.967995,21.268000

In [55]:
df[ (df.state == 'AL') & (df.price < 150) ]

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335

In [56]:
(df.state == 'AL') # & (df.price < 150)

0      True
1     False
2     False
3     False
4     False
      ...
91    False
92    False
93    False
94    False
95    False
Name: state, Length: 96, dtype: bool

In [59]:
selecao = (df.state == 'AL') & (df.price < 150)

df[ selecao ]

,state,year,cpi,population,packs,income,tax,price,taxs
0,AL,1985,1.076,3973000,116.486282,46014968,32.500004,102.181671,33.348335

## Selecionar Colunas e Linhas

In [60]:
df[ df.price < 90 ]['price']

14    87.001251
24    84.967995
Name: price, dtype: float64

In [61]:
df[ df.price < 90 ].price

14    87.001251
24    84.967995
Name: price, dtype: float64

In [62]:
df[ df.price < 90 ][ ['income', 'price'] ]

      income      price
14  42703144  87.001251
24  79104656  84.967995

### **Não é um boa prática**

In [63]:
df[ ['income', 'price'] ][ df.price < 90 ]

      income      price
14  42703144  87.001251
24  79104656  84.967995

## Operação Fechada

In [65]:
df[ df.price < 90 ][ ['income', 'price'] ].head(1)

      income      price
14  42703144  87.001251

In [66]:
df[ df.price < 90 ][ ['income', 'price'] ].describe()

             income      price
count  2.000000e+00   2.000000
mean   6.090390e+07  85.984623
std    2.573976e+07   1.437729
min    4.270314e+07  84.967995
25%    5.180352e+07  85.476309
50%    6.090390e+07  85.984623
75%    7.000428e+07  86.492937
max    7.910466e+07  87.001251

In [67]:
df2 = df[ df.price < 90 ][ ['income', 'price'] ]

df2.head()

      income      price
14  42703144  87.001251
24  79104656  84.967995