<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Exemplo_CASchools_selecao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/CASchools.csv")
df = df.drop(columns="rownames")
df.head()

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024

# Explorando a estrutura

In [ ]:
df.shape

(420, 14)

In [ ]:
len(df)

420

In [ ]:
df.columns

Index(['district', 'school', 'county', 'grades', 'students', 'teachers',
       'calworks', 'lunch', 'computer', 'expenditure', 'income', 'english',
       'read', 'math'],
      dtype='object')

In [ ]:
df.describe(include='all')

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
count,420.000000,420,420,420,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000
unique,NaN,409,45,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Mountain View Elementary,Sonoma,KK-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,3,29,359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,67472.809524,NaN,NaN,NaN,2628.792857,129.067376,13.246042,44.705237,303.383333,5312.407541,15.316588,15.768155,654.970477,653.342619
std,3466.994655,NaN,NaN,NaN,3913.104985,187.912679,11.454821,27.123381,441.341298,633.937053,7.225890,18.285927,20.107980,18.754202
min,61382.000000,NaN,NaN,NaN,81.000000,4.850000,0.000000,0.000000,0.000000,3926.069580,5.335000,0.000000,604.500000,605.400024
25%,64307.750000,NaN,NaN,NaN,379.000000,19.662499,4.395375,23.282200,46.000000,4906.180054,10.639000,1.940807,640.400024,639.375015
50%,67760.500000,NaN,NaN,NaN,950.500000,48.564999,10.520450,41.750700,117.500000,5214.516602,13.727800,8.777634,655.750000,652.449982
75%,70419.000000,NaN,NaN,NaN,3008.000000,146.350002,18.981350,66.864725,375.250000,5601.401367,17.629001,22.970003,668.725006,665.849991
max,75440.000000,NaN,NaN,NaN,27176.000000,1429.000000,78.994202,100.000000,3324.000000,7711.506836,55.327999,85.539719,704.000000,709.500000

In [ ]:
df.dtypes

district         int64
school          object
county          object
grades          object
students         int64
teachers       float64
calworks       float64
lunch          float64
computer         int64
expenditure    float64
income         float64
english        float64
read           float64
math           float64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   district     420 non-null    int64
 1   school       420 non-null    object
 2   county       420 non-null    object
 3   grades       420 non-null    object
 4   students     420 non-null    int64
 5   teachers     420 non-null    float64
 6   calworks     420 non-null    float64
 7   lunch        420 non-null    float64
 8   computer     420 non-null    int64
 9   expenditure  420 non-null    float64
 10  income       420 non-null    float64
 11  english      420 non-null    float64
 12  read         420 non-null    float64
 13  math         420 non-null    float64
dtypes: float64(8), int64(3), object(3)
memory usage: 46.1+ KB

# Automatic EDA

Opções: Sweetviz, Autoviz, YData Profiling (antigo Pandas Profiling)

In [ ]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 8.1 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 24.8 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 61.6 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 44.3 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.4 MB/s eta 0:00:00
Downloading puremagic-2.0.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 4.9 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.0.0 visions-0.8.1 ydata-profiling-4.18.1

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="EDA do DataFrame df")
profile.to_notebook_iframe()

# Seleção de Colunas, Seleção de Linhas e de Linhas e Colunas

<img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" width=320, align="center">
<img src="https://pandas.pydata.org/docs/_images/03_subset_columns_rows.svg" width=320, align="center">

## Seleção de 1 Coluna

In [3]:
df.head()

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024

In [4]:
df['students']

0       195
1       240
2      1550
3       243
4      1335
       ...
415     984
416    3724
417     441
418     101
419    1778
Name: students, Length: 420, dtype: int64

In [9]:
type(df['students']), type(df)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [12]:
var = 'students'

df.students, df['students'], df[var]

(0       195
 1       240
 2      1550
 3       243
 4      1335
        ...
 415     984
 416    3724
 417     441
 418     101
 419    1778
 Name: students, Length: 420, dtype: int64,
 0       195
 1       240
 2      1550
 3       243
 4      1335
        ...
 415     984
 416    3724
 417     441
 418     101
 419    1778
 Name: students, Length: 420, dtype: int64,
 0       195
 1       240
 2      1550
 3       243
 4      1335
        ...
 415     984
 416    3724
 417     441
 418     101
 419    1778
 Name: students, Length: 420, dtype: int64)

In [17]:
df.students.sum(), df.students.mean(), df.students.var(), df.students.quantile(0.1)

(np.int64(1104093),
 np.float64(2628.792857142857),
 15312390.622860562,
 np.float64(164.0))

In [18]:
df.students / df.students.max()

0      0.007175
1      0.008831
2      0.057036
3      0.008942
4      0.049124
         ...
415    0.036208
416    0.137033
417    0.016228
418    0.003717
419    0.065425
Name: students, Length: 420, dtype: float64

## Cuidado: Series x DataFrame

In [19]:
df.students, df['students'], df[['students']]

(0       195
 1       240
 2      1550
 3       243
 4      1335
        ...
 415     984
 416    3724
 417     441
 418     101
 419    1778
 Name: students, Length: 420, dtype: int64,
 0       195
 1       240
 2      1550
 3       243
 4      1335
        ...
 415     984
 416    3724
 417     441
 418     101
 419    1778
 Name: students, Length: 420, dtype: int64,
      students
 0         195
 1         240
 2        1550
 3         243
 4        1335
 ..        ...
 415       984
 416      3724
 417       441
 418       101
 419      1778

 [420 rows x 1 columns])

In [20]:
df.students.mean(), df['students'].mean(), df[['students']].mean()

(np.float64(2628.792857142857),
 np.float64(2628.792857142857),
 students    2628.792857
 dtype: float64)

In [23]:
print(df['students'])

0       195
1       240
2      1550
3       243
4      1335
       ...
415     984
416    3724
417     441
418     101
419    1778
Name: students, Length: 420, dtype: int64

In [30]:
%%script echo off
df['students'].columns

off

In [24]:
print(df[['students']])

     students
0         195
1         240
2        1550
3         243
4        1335
..        ...
415       984
416      3724
417       441
418       101
419      1778

[420 rows x 1 columns]

In [31]:
df[['students']].columns

Index(['students'], dtype='object')

In [34]:
df['students'].nlargest(5)

48     27176
34     25151
159    21338
62     20927
106    19402
Name: students, dtype: int64

In [36]:
df.grades.value_counts(), df.school.value_counts()

(grades
 KK-08    359
 KK-06     61
 Name: count, dtype: int64,
 school
 Mountain View Elementary                  3
 Lakeside Union Elementary                 3
 Pleasant Valley Elementary                2
 Jefferson Elementary                      2
 Ocean View Elementary                     2
                                          ..
 Redwood City Elementary                   1
 Twain Harte-Long Barn Union Elementary    1
 Turlock Joint Elementary                  1
 General Shafter Elementary                1
 Cuddeback Union Elementary                1
 Name: count, Length: 409, dtype: int64)

## Seleção de $n$ colunas

In [25]:
df.head()

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024

In [27]:
df[ ['students', 'computer'] ]

     students  computer
0         195        67
1         240       101
2        1550       169
3         243        85
4        1335       171
..        ...       ...
415       984       195
416      3724       721
417       441        45
418       101        14
419      1778       313

[420 rows x 2 columns]

In [32]:
df[ ['students', 'computer'] ].mean()

students    2628.792857
computer     303.383333
dtype: float64

In [33]:
selecao = ['students', 'computer']

df[ selecao ]

     students  computer
0         195        67
1         240       101
2        1550       169
3         243        85
4        1335       171
..        ...       ...
415       984       195
416      3724       721
417       441        45
418       101        14
419      1778       313

[420 rows x 2 columns]

## Seleção de Linhas

In [41]:
df[ df.students > 25000 ]

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
34,67819,Ontario-Montclair Elementary,San Bernardino,KK-08,25151,1186.699951,17.442600,80.195602,1713,5117.039551,11.722225,49.823071,625.400024,626.799988
48,63321,Bakersfield City Elementary,Kern,KK-08,27176,1429.000000,39.218399,84.294998,3324,5864.366211,12.109128,28.863705,631.599976,629.500000

In [42]:
df[ (df.students > 10000) & (df.computer > 3000) ]

,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
48,63321,Bakersfield City Elementary,Kern,KK-08,27176,1429.0,39.218399,84.294998,3324,5864.366211,12.109128,28.863705,631.599976,629.5

In [43]:
(df.students > 10000) & (df.computer > 3000)

0      False
1      False
2      False
3      False
4      False
       ...
415    False
416    False
417    False
418    False
419    False
Length: 420, dtype: bool

## Selecionar Colunas e Linhas

In [44]:
df[ df.students > 25000 ][['students', 'computer']]

    students  computer
34     25151      1713
48     27176      3324

In [45]:
df[ df.students > 25000 ].students

34    25151
48    27176
Name: students, dtype: int64