<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Hands_on_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Carregando o dataset 'Tips'

df = sns.load_dataset('tips')
display(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Exemplos de `pd.melt`

#### Exemplo 1.1: `melt` - De-normalizando `total_bill` e `tip`

Neste primeiro exemplo, vamos usar `pd.melt` para transformar as colunas `total_bill` e `tip` de formato 'largo' para 'longo'. Manteremos as colunas categóricas (`sex`, `smoker`, `day`, `time`, `size`) como identificadores (`id_vars`).

In [5]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Usando pd.melt para 'desempilhar' total_bill e tip
df_melted_1 = pd.melt(df,
                     id_vars=['sex', 'smoker', 'day', 'time', 'size'],
                     value_vars=['total_bill', 'tip'],
                     var_name='metrica',
                     value_name='valor')

print("\nDataFrame após pd.melt (Exemplo 1.1 - df_melted_1.head()):\n")
display(df_melted_1.head())

print("Valores únicos na nova coluna 'metrica':", df_melted_1['metrica'].unique())

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.melt (Exemplo 1.1 - df_melted_1.head()):

      sex smoker  day    time  size     metrica  valor
0  Female     No  Sun  Dinner     2  total_bill  16.99
1    Male     No  Sun  Dinner     3  total_bill  10.34
2    Male     No  Sun  Dinner     3  total_bill  21.01
3    Male     No  Sun  Dinner     2  total_bill  23.68
4  Female     No  Sun  Dinner     4  total_bill  24.59

Valores únicos na nova coluna 'metrica': ['total_bill' 'tip']

#### Exemplo 1.2: `melt` - De-normalizando `total_bill`, `tip` e `size`

Vamos agora expandir o exemplo anterior e incluir a coluna `size` (`tamanho do grupo`) como uma das variáveis a serem derretidas (`value_vars`). Isso nos permitirá comparar como `total_bill`, `tip` e `size` se distribuem em um formato longo.

In [6]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Usando pd.melt para 'desempilhar' total_bill, tip e size
df_melted_2 = pd.melt(df,
                     id_vars=['sex', 'smoker', 'day', 'time'],
                     value_vars=['total_bill', 'tip', 'size'],
                     var_name='metrica',
                     value_name='valor')

print("\nDataFrame após pd.melt (Exemplo 1.2 - df_melted_2.head()):\n")
display(df_melted_2.head())

print("Valores únicos na nova coluna 'metrica':", df_melted_2['metrica'].unique())

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.melt (Exemplo 1.2 - df_melted_2.head()):

      sex smoker  day    time     metrica  valor
0  Female     No  Sun  Dinner  total_bill  16.99
1    Male     No  Sun  Dinner  total_bill  10.34
2    Male     No  Sun  Dinner  total_bill  21.01
3    Male     No  Sun  Dinner  total_bill  23.68
4  Female     No  Sun  Dinner  total_bill  24.59

Valores únicos na nova coluna 'metrica': ['total_bill' 'tip' 'size']

#### Exemplo 1.3: `melt` - Com todos os `id_vars` e foco em `total_bill` e `tip`

Neste exemplo, vamos manter todas as outras colunas (exceto `total_bill` e `tip`) como `id_vars`, garantindo que cada linha do DataFrame original tenha uma correspondência em múltiplas linhas no DataFrame derretido, uma para `total_bill` e outra para `tip`.

In [7]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Obtendo todas as colunas que não serão 'derretidas'
all_cols = df.columns.tolist()
value_vars_to_melt = ['total_bill', 'tip']
id_vars_to_keep = [col for col in all_cols if col not in value_vars_to_melt]

df_melted_3 = pd.melt(df,
                     id_vars=id_vars_to_keep,
                     value_vars=value_vars_to_melt,
                     var_name='tipo_valor',
                     value_name='valor_monetario')

print("\nDataFrame após pd.melt (Exemplo 1.3 - df_melted_3.head()):\n")
display(df_melted_3.head())

print("Valores únicos na nova coluna 'tipo_valor':", df_melted_3['tipo_valor'].unique())

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.melt (Exemplo 1.3 - df_melted_3.head()):

      sex smoker  day    time  size  tipo_valor  valor_monetario
0  Female     No  Sun  Dinner     2  total_bill            16.99
1    Male     No  Sun  Dinner     3  total_bill            10.34
2    Male     No  Sun  Dinner     3  total_bill            21.01
3    Male     No  Sun  Dinner     2  total_bill            23.68
4  Female     No  Sun  Dinner     4  total_bill            24.59

Valores únicos na nova coluna 'tipo_valor': ['total_bill' 'tip']

### Exemplos de `pd.pivot_table`

#### Exemplo 2.1: `pivot_table` - Gorjeta Média por Dia e Sexo

Começaremos com um `pivot_table` simples para calcular a *gorjeta média* (`tip`) por `day` (linhas) e `sex` (colunas), usando `mean` como função de agregação (`aggfunc`).

In [8]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Calculando a gorjeta média por dia e sexo
df_pivot_1 = pd.pivot_table(df,
                              values='tip',
                              index='day',
                              columns='sex',
                              aggfunc='mean')

print("\nDataFrame após pd.pivot_table (Exemplo 2.1 - Gorjeta Média por Dia e Sexo):\n")
display(df_pivot_1)

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.pivot_table (Exemplo 2.1 - Gorjeta Média por Dia e Sexo):

/tmp/ipykernel_11518/3688809758.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_pivot_1 = pd.pivot_table(df,

sex       Male    Female
day
Thur  2.980333  2.575625
Fri   2.693000  2.781111
Sat   3.083898  2.801786
Sun   3.220345  3.367222

#### Exemplo 2.2: `pivot_table` - Múltiplas Agregações (Média e Soma) de Gorjetas por Dia e Sexo

Neste exemplo, vamos estender o uso de `pivot_table` para realizar múltiplas funções de agregação (`aggfunc=['mean', 'sum']`) sobre a coluna `tip`, ainda dividindo por `day` e `sex`. Isso demonstra como obter diferentes estatísticas em uma única tabela dinâmica.

In [27]:
df_pivot_2 = pd.pivot(df,     values='tip',
                              columns='sex')
df_pivot_2

sex  Male  Female
0     NaN    1.01
1    1.66     NaN
2    3.50     NaN
3    3.31     NaN
4     NaN    3.61
..    ...     ...
239  5.92     NaN
240   NaN    2.00
241  2.00     NaN
242  1.75     NaN
243   NaN    3.00

[244 rows x 2 columns]

In [9]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Calculando média e soma das gorjetas por dia e sexo
df_pivot_2 = pd.pivot_table(df,
                              values='tip',
                              index='day',
                              columns='sex',
                              aggfunc=['mean', 'sum'])

print("\nDataFrame após pd.pivot_table (Exemplo 2.2 - Média e Soma de Gorjetas por Dia e Sexo):\n")
display(df_pivot_2)

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.pivot_table (Exemplo 2.2 - Média e Soma de Gorjetas por Dia e Sexo):

/tmp/ipykernel_11518/1865196775.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_pivot_2 = pd.pivot_table(df,
/tmp/ipykernel_11518/1865196775.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_pivot_2 = pd.pivot_table(df,

          mean               sum
sex       Male    Female    Male Female
day
Thur  2.980333  2.575625   89.41  82.42
Fri   2.693000  2.781111   26.93  25.03
Sat   3.083898  2.801786  181.95  78.45
Sun   3.220345  3.367222  186.78  60.61

#### Exemplo 2.3: `pivot_table` - Conta Total Média por Dia, Tempo e Sexo

Para um exemplo mais complexo, usaremos `day` e `time` como índices combinados e `sex` como colunas, para calcular a `total_bill` média (`aggfunc='mean'`). Isso mostra como usar múltiplos níveis para `index` e `columns`.

In [10]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Calculando a conta total média por dia, tempo e sexo
df_pivot_3 = pd.pivot_table(df,
                              values='total_bill',
                              index=['day', 'time'],
                              columns='sex',
                              aggfunc='mean')

print("\nDataFrame após pd.pivot_table (Exemplo 2.3 - Conta Total Média por Dia, Tempo e Sexo):\n")
display(df_pivot_3)

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.pivot_table (Exemplo 2.3 - Conta Total Média por Dia, Tempo e Sexo):

/tmp/ipykernel_11518/2721257185.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df_pivot_3 = pd.pivot_table(df,

sex               Male     Female
day  time
Thur Lunch   18.714667  16.648710
     Dinner        NaN  18.780000
Fri  Lunch   11.386667  13.940000
     Dinner  23.487143  14.310000
Sat  Dinner  20.802542  19.680357
Sun  Dinner  21.887241  19.872222

#### Exemplo 2.4: `pivot_table`

In [15]:
print("### Exemplo de Tabela de Frequência 1: Frequência Simples por Dia\n")
# Tabela de frequência para a coluna 'day' usando value_counts()
freq_day = df['day'].value_counts()
print("Frequência de clientes por dia da semana:\n")
display(freq_day)

print("\n### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo\n")
# Tabela de frequência cruzada entre 'day' e 'sex' usando pd.crosstab
freq_day_sex = pd.crosstab(index=df['day'], columns=df['sex'])
print("Frequência de clientes por dia da semana e sexo:\n")
display(freq_day_sex)

### Exemplo de Tabela de Frequência 1: Frequência Simples por Dia

Frequência de clientes por dia da semana:

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo

Frequência de clientes por dia da semana e sexo:

sex   Male  Female
day
Thur    30      32
Fri     10       9
Sat     59      28
Sun     58      18

In [16]:
print("\n### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo\n")
# Tabela de frequência cruzada entre 'day' e 'sex' usando pd.crosstab
freq_day_sex = pd.crosstab(index=df['day'], columns=df['sex'], margins=True)
print("Frequência de clientes por dia da semana e sexo:\n")
display(freq_day_sex)

### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo

Frequência de clientes por dia da semana e sexo:

sex   Male  Female  All
day
Thur    30      32   62
Fri     10       9   19
Sat     59      28   87
Sun     58      18   76
All    157      87  244

In [17]:
print("\n### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo\n")
# Tabela de frequência cruzada entre 'day' e 'sex' usando pd.crosstab
freq_day_sex = pd.crosstab(index=df['day'], columns=df['sex'], margins=True, normalize=True)
print("Frequência de clientes por dia da semana e sexo:\n")
display(freq_day_sex)

### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo

Frequência de clientes por dia da semana e sexo:

sex       Male    Female       All
day
Thur  0.122951  0.131148  0.254098
Fri   0.040984  0.036885  0.077869
Sat   0.241803  0.114754  0.356557
Sun   0.237705  0.073770  0.311475
All   0.643443  0.356557  1.000000

In [22]:
print("\n### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo\n")
# Tabela de frequência cruzada entre 'day' e 'sex' usando pd.crosstab
freq_day_sex = pd.crosstab(index=df['day'], columns=df['sex'], values=df['tip'], aggfunc='sum', margins=True)
print("Frequência de clientes por dia da semana e sexo:\n")
display(freq_day_sex)

### Exemplo de Tabela de Frequência 2: Tabela Cruzada por Dia e Sexo

Frequência de clientes por dia da semana e sexo:

sex     Male  Female     All
day
Thur   89.41   82.42  171.83
Fri    26.93   25.03   51.96
Sat   181.95   78.45  260.40
Sun   186.78   60.61  247.39
All   485.07  246.51  731.58

In [ ]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Calculando a conta total média por dia, tempo e sexo
df_pivot_3 = pd.pivot_table(df,
                              values='total_bill',
                              index=['day', 'time'],
                              columns='sex',
                              aggfunc='mean')

print("\nDataFrame após pd.pivot_table (Exemplo 2.3 - Conta Total Média por Dia, Tempo e Sexo):\n")
display(df_pivot_3)

### Exemplo 1: `melt` - De-normalizando `total_bill` e `tip`

Neste primeiro exemplo, vamos usar `pd.melt` para transformar as colunas `total_bill` e `tip` de formato 'largo' para 'longo'. Isso significa que teremos uma nova coluna que indicará se o valor é referente à conta total (`total_bill`) ou à gorjeta (`tip`), e outra coluna com os respectivos valores. Isso é útil para comparar essas duas métricas.

Manteremos as colunas categóricas (`sex`, `smoker`, `day`, `time`, `size`) como identificadores (`id_vars`).

In [4]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Usando pd.melt para 'desempilhar' total_bill e tip
df_melted = pd.melt(df,
                    id_vars=['sex', 'smoker', 'day', 'time', 'size'],
                    value_vars=['total_bill', 'tip'],
                    var_name='metric',
                    value_name='value')

print("\nDataFrame após pd.melt (df_melted.head()):\n")
display(df_melted.head())

print("\nValores únicos na nova coluna 'metric':", df_melted['metric'].unique())

DataFrame Original (df.head()):

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

DataFrame após pd.melt (df_melted.head()):

      sex smoker  day    time  size      metric  value
0  Female     No  Sun  Dinner     2  total_bill  16.99
1    Male     No  Sun  Dinner     3  total_bill  10.34
2    Male     No  Sun  Dinner     3  total_bill  21.01
3    Male     No  Sun  Dinner     2  total_bill  23.68
4  Female     No  Sun  Dinner     4  total_bill  24.59

Valores únicos na nova coluna 'metric': ['total_bill' 'tip']

### Exemplo 2: `pivot_table` - Agregando e Reshapando Gorjetas Médias por Dia e Sexo

Agora, vamos usar `pivot_table` para resumir os dados. `pivot_table` é uma ferramenta poderosa para criar tabelas dinâmicas, permitindo que você especifique o índice (linhas), colunas e valores, além de uma função de agregação (`aggfunc`).

Neste exemplo, calcularemos a *gorjeta média* (`tip`) por `day` (dias da semana) e `sex` (gênero), transformando 'day' nas linhas e 'sex' nas colunas.

In [ ]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# Calculando a gorjeta média por dia e sexo usando pivot_table
df_pivot_mean_tip = pd.pivot_table(df,
                                   values='tip',
                                   index='day',
                                   columns='sex',
                                   aggfunc='mean')

print("\nDataFrame após pd.pivot_table (Gorjeta Média por Dia e Sexo):\n")
display(df_pivot_mean_tip)

### Exemplo 3: Combinando `melt` e `pivot_table` para Análise Avançada de Métricas Agregadas

Para um exemplo mais complexo, vamos primeiro calcular as médias de `total_bill` e `tip` para cada combinação de `day` e `time`.

Em seguida, usaremos `melt` nesse DataFrame agregado para ter uma única coluna de 'métrica' (representando 'total_bill' médio e 'tip' médio) e uma coluna de 'valor'.

Finalmente, usaremos `pivot_table` para reorganizar esses dados, tendo o `day` como índice, a `metric` como colunas e o `value` como os dados, permitindo uma comparação lado a lado das médias de conta total e gorjeta por dia e tempo.

In [ ]:
print("DataFrame Original (df.head()):\n")
display(df.head())

# 1. Agrupar por 'day' e 'time' e calcular a média de 'total_bill' e 'tip'
df_aggregated = df.groupby(['day', 'time'])[['total_bill', 'tip']].mean().reset_index()

print("\nDataFrame Agregado (df_aggregated.head()):\n")
display(df_aggregated.head())

# 2. Usar melt no DataFrame agregado para 'desempilhar' 'total_bill' e 'tip'
df_melted_aggregated = pd.melt(df_aggregated,
                               id_vars=['day', 'time'],
                               value_vars=['total_bill', 'tip'],
                               var_name='metric',
                               value_name='average_value')

print("\nDataFrame Agregado após pd.melt (df_melted_aggregated.head()):\n")
display(df_melted_aggregated.head())

# 3. Usar pivot_table para reorganizar o DataFrame derretido
# Agora podemos ver facilmente o total_bill médio vs. tip médio por dia e tempo
df_final_pivot = pd.pivot_table(df_melted_aggregated,
                                 index=['day', 'time'],
                                 columns='metric',
                                 values='average_value')

print("\nDataFrame Final após pd.pivot_table (comparação de métricas médias):\n")
display(df_final_pivot)