<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/handson_20260319.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Índices, Localizadores `.loc` e `.iloc`**


## Sumário

* Seleções (`read-only`), empregue

>> `df[ row-selection-criteria ][ columns-selection-list ]`

>> Exemplos: **`df[ df.age < 16 ][['name','age']]`**

* Alterações (`update`) por chave (rótulo) do índice ou por posição, empregue

>> `df.loc[ rows-key, column-key (name) ]...`, ou

>> Exemplos: **`df.loc[ 'VW 60', 'mpg']`**

>> `df.iloc[ rows-position, column-position ]...`

>> Exemplos: **`df.iloc[ 5, 1:4 ]`**

* Alterações (`update`) com seleção de dados, empregue por chave (rótulo) do índice ou por posição, empregue

>> `df.loc[ row-selection-criteria, column-key (name) ]...`,  ou

>> `df.iloc[ row-selection-criteria.index, column-position ]...`

* Query

>> `df.query[ ' non-predix row-selection-criteria  ' ]`, como `df.query['blood="AB"']`

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv',index_col='rownames')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

# Seleções de dados

Alternativamente a

`df[ row-selection-criteria ][ columns-selection-list ]`

você pode fazer,

`df.loc[ row-selection-criteria, column-key (name) ]` ou

`df.iloc[ row-selection-criteria.index, column-position ]`

In [5]:
df[ df.cyl == 8 ][['mpg','cyl','hp']].head()

                    mpg  cyl   hp

Hornet Sportabout  18.7    8  175
Duster 360         14.3    8  245
Merc 450SE         16.4    8  180
Merc 450SL         17.3    8  180
Merc 450SLC        15.2    8  180

In [6]:
df.loc[ df.cyl == 8 , ['mpg','cyl','hp'] ].head()

                    mpg  cyl   hp

Hornet Sportabout  18.7    8  175
Duster 360         14.3    8  245
Merc 450SE         16.4    8  180
Merc 450SL         17.3    8  180
Merc 450SLC        15.2    8  180

In [9]:
# Embora funcione, não é uma boa solução:
df[ df.cyl == 8 ][['mpg','cyl','hp']].head()
df.loc[ df.cyl == 8 , ['mpg','cyl','hp'] ].head()

display(df.loc[ df.cyl == 8 ].head())
display(df.loc[ df.cyl == 8 ][ ['mpg','cyl','hp'] ].head())

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Hornet Sportabout,18.7,8,360.0,175,3.15,3.44,17.02,0,0,3,2
Duster 360,14.3,8,360.0,245,3.21,3.57,15.84,0,0,3,4
Merc 450SE,16.4,8,275.8,180,3.07,4.07,17.40,0,0,3,3
Merc 450SL,17.3,8,275.8,180,3.07,3.73,17.60,0,0,3,3
Merc 450SLC,15.2,8,275.8,180,3.07,3.78,18.00,0,0,3,3

                    mpg  cyl   hp

Hornet Sportabout  18.7    8  175
Duster 360         14.3    8  245
Merc 450SE         16.4    8  180
Merc 450SL         17.3    8  180
Merc 450SLC        15.2    8  180

# Selecionando nomes das colunas

In [12]:
[ col for col in df.columns if col.startswith('d') ]

['disp', 'drat']

In [13]:
cols = [ col for col in df.columns if col.startswith('d') ]
df[ cols ]

                      disp  drat

Mazda RX4            160.0  3.90
Mazda RX4 Wag        160.0  3.90
Datsun 710           108.0  3.85
Hornet 4 Drive       258.0  3.08
Hornet Sportabout    360.0  3.15
Valiant              225.0  2.76
Duster 360           360.0  3.21
Merc 240D            146.7  3.69
Merc 230             140.8  3.92
Merc 280             167.6  3.92
Merc 280C            167.6  3.92
Merc 450SE           275.8  3.07
Merc 450SL           275.8  3.07
Merc 450SLC          275.8  3.07
Cadillac Fleetwood   472.0  2.93
Lincoln Continental  460.0  3.00
Chrysler Imperial    440.0  3.23
Fiat 128              78.7  4.08
Honda Civic           75.7  4.93
Toyota Corolla        71.1  4.22
Toyota Corona        120.1  3.70
Dodge Challenger     318.0  2.76
AMC Javelin          304.0  3.15
Camaro Z28           350.0  3.73
Pontiac Firebird     400.0  3.08
Fiat X1-9             79.0  4.08
Porsche 914-2        120.3  4.43
Lotus Europa          95.1  3.77
Ford Pantera L       351.0  4.22
Ferrari Dino         145.0  3.62
Maserati Bora        301.0  3.54
Volvo 142E           121.0  4.11

# Selecionando Proporções

In [14]:
print(f'Percentual de veículos com 4 cyl: {len(df[ df.cyl == 4 ]) / len(df) * 100:.2f} %')
print(f'Percentual da potência total dos veículos com 4 cyl: {df[ df.cyl == 4 ].hp.sum() / df.hp.sum() * 100:.2f} %')

Percentual de veículos com 4 cyl: 34.38 %
Percentual da potência total dos veículos com 4 cyl: 19.37 %

In [ ]:
# Seleção de pertinência

In [15]:
df[ df.cyl.isin([4,6]) ]

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb

Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
Valiant         18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
Merc 240D       24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2
Merc 230        22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2
Merc 280        19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4
Merc 280C       17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4
Fiat 128        32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1
Honda Civic     30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1
Toyota Corona   21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1
Fiat X1-9       27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1
Porsche 914-2   26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2

# Mais sobre estatísticas descritivas

In [18]:
df.mean(axis=1 skipna = False)

Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Datsun 710             23.598182
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Valiant                35.049091
Duster 360             59.720000
Merc 240D              24.634545
Merc 230               27.233636
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Cadillac Fleetwood     66.232727
Lincoln Continental    66.058545
Chrysler Imperial      65.972273
Fiat 128               19.440909
Honda Civic            17.742273
Toyota Corolla         18.814091
Toyota Corona          24.888636
Dodge Challenger       47.240909
AMC Javelin            46.007727
Camaro Z28             58.752727
Pontiac Firebird       57.379545
Fiat X1-9              18.928636
Porsche 914-2          24.779091
Lotus Europa           24.880273
Ford Pantera L         60.971818
Ferrari Dino           34.508182
Maserati Bora          63.155455
Volvo 142E             26.262727
dtype: float64

# Atualizando valores

Seleções de dados do modo

`df[ row-selection-criteria ][ columns-selection-list ]`

criam uma *visão dos dados*, e não permitem alterações. Por isso, alterações devem sempre ser feitas com os operadores de localização `.loc` ou `.iloc`.

In [19]:
df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv',index_col='rownames')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

## Novas colunas e séries completas

Novas colunas ou alterações de todas as linhas podem ser feitas diretamente, pois não envolvem uma seleção dos dados.

In [22]:
df['kmpg'] = 1.6 * df['mpg']
df['hp'] = df['hp'] * 10
df['hp/mpg'] = df['hp'] / df['mpg']
df['ones'] = 1
df['array'] = np.arange(len(df))
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,21.4,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

## `df.copy()`

In [23]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,21.4,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [24]:
df.loc['Hornet 4 Drive', 'mpg'] = 22
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,22.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [25]:
df2 = df
df2.loc['Hornet 4 Drive','mpg'] = 99
df2.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [26]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [29]:
id(df), id(df2)

(132842942291632, 132842885677280)

In [28]:
df2 = df.copy()
df2.loc['Hornet 4 Drive','mpg'] = 999
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

## Falhas nas alterações com views

In [30]:
df[(df.gear > 0)]['mpg'] = 99
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [32]:
df[(df.gear == 4)]['mpg'] = 99
df.head()

/tmp/ipykernel_31327/1856020194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[(df.gear == 4)]['mpg'] = 99

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [33]:
df.loc['Datsun 710':'Ford Pantera L']['hp'] = 999
df.head()

/tmp/ipykernel_31327/2323878747.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc['Datsun 710':'Ford Pantera L']['hp'] = 999
/tmp/ipykernel_31327/2323878747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc['Datsun 710':'Ford Pantera L']['hp'] = 999

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,93000,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,110000,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,175000,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

# Alterações de dados corretas

In [34]:
df.loc['Datsun 710':'Ford Pantera L','hp'] = 999
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,999,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,99.0,6,258.0,999,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,999,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [35]:
df.iloc[3,0] = -100
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,21.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,999,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,-100.0,6,258.0,999,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,999,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

In [36]:
df.loc[df.cyl == 6,'mpg'] = -1
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,kmpg,hp/mpg,ones,array
,,,,,,,,,,,,,,,
Mazda RX4,-1.0,6,160.0,110000,3.90,2.620,16.46,0,1,4,4,33.60,5238.095238,1,0
Mazda RX4 Wag,-1.0,6,160.0,110000,3.90,2.875,17.02,0,1,4,4,33.60,5238.095238,1,1
Datsun 710,22.8,4,108.0,999,3.85,2.320,18.61,1,1,4,1,36.48,4078.947368,1,2
Hornet 4 Drive,-1.0,6,258.0,999,3.08,3.215,19.44,1,0,3,1,34.24,5140.186916,1,3
Hornet Sportabout,18.7,8,360.0,999,3.15,3.440,17.02,0,0,3,2,29.92,9358.288770,1,4

# Insert Rows

## Usando .loc

In [38]:
df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv',index_col='rownames')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [40]:
new_row = dict(df.iloc[0])
new_row

{'mpg': np.float64(21.0),
 'cyl': np.float64(6.0),
 'disp': np.float64(160.0),
 'hp': np.float64(110.0),
 'drat': np.float64(3.9),
 'wt': np.float64(2.62),
 'qsec': np.float64(16.46),
 'vs': np.float64(0.0),
 'am': np.float64(1.0),
 'gear': np.float64(4.0),
 'carb': np.float64(4.0)}

In [41]:
df.loc['New Car 1'] = new_row
df.tail()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Ford Pantera L,15.8,8.0,351.0,264.0,4.22,3.17,14.50,0.0,1.0,5.0,4.0
Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.77,15.50,0.0,1.0,5.0,6.0
Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.57,14.60,0.0,1.0,5.0,8.0
Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.78,18.60,1.0,1.0,4.0,2.0
New Car 1,21.0,6.0,160.0,110.0,3.90,2.62,16.46,0.0,1.0,4.0,4.0

## Caso de índices numéricos

In [42]:
df.reset_index(inplace=True)
df.head()

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0

In [44]:
df.rename(columns={'':'model'},inplace=True)
df.head( )

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0

In [45]:
new_row = {
 'model' : 'New Car 3',
 'mpg': np.float64(-1.0),
 'cyl': np.float64(6.0),
 'disp': np.float64(160.0),
 'hp': np.float64(1100.0),
 'drat': np.float64(3.9),
 'wt': np.float64(2.62),
 'qsec': np.float64(16.46),
 'vs': np.float64(0.0),
 'am': np.float64(1.0),
 'gear': np.float64(4.0),
 'carb': np.float64(4.0),
 'kmpg': np.float64(33.6),
 'hp/mpg': np.float64(52.38095238095238)}

df.loc[len(df)] = new_row
df.tail()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
29,Ferrari Dino,19.7,6.0,145.0,175.0,3.62,2.77,15.50,0.0,1.0,5.0,6.0
30,Maserati Bora,15.0,8.0,301.0,335.0,3.54,3.57,14.60,0.0,1.0,5.0,8.0
31,Volvo 142E,21.4,4.0,121.0,109.0,4.11,2.78,18.60,1.0,1.0,4.0,2.0
32,New Car 1,21.0,6.0,160.0,110.0,3.90,2.62,16.46,0.0,1.0,4.0,4.0
33,New Car 3,-1.0,6.0,160.0,1100.0,3.90,2.62,16.46,0.0,1.0,4.0,4.0

# Delete Rows

In [49]:
display(df.head())
df.index.delete(1)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0

Index([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
      dtype='int64')

In [51]:
display(df.head())
df = df.drop(df.index[0])
display(df.head())

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6.0,160.0,110.0,3.90,2.620,16.46,0.0,1.0,4.0,4.0
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4 Wag,21.0,6.0,160.0,110.0,3.90,2.875,17.02,0.0,1.0,4.0,4.0
2,Datsun 710,22.8,4.0,108.0,93.0,3.85,2.320,18.61,1.0,1.0,4.0,1.0
3,Hornet 4 Drive,21.4,6.0,258.0,110.0,3.08,3.215,19.44,1.0,0.0,3.0,1.0
4,Hornet Sportabout,18.7,8.0,360.0,175.0,3.15,3.440,17.02,0.0,0.0,3.0,2.0
5,Valiant,18.1,6.0,225.0,105.0,2.76,3.460,20.22,1.0,0.0,3.0,1.0

# Iterando sobre o dataframe

## `iloc`

In [53]:
df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv',index_col='rownames')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [54]:
for i in range(0,len(df)):
  for j in range(0,len(df.columns)):
    if df.iloc[i,j] > 200:
      print( df.iloc[i,j] )

258.0
360.0
225.0
360.0
245
275.8
275.8
275.8
472.0
205
460.0
215
440.0
230
318.0
304.0
350.0
245
400.0
351.0
264
301.0
335

## `.loc`

In [55]:
df.keys()

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [ ]:
for line in df.index:
  for col in df:
    if df.loc[line,col] > 200:
      print( df.loc[line,col] )

258.0
360.0
225.0
360.0
245
275.8
275.8
275.8
472.0
205
460.0
215
440.0
230
318.0
304.0
350.0
245
400.0
351.0
264
301.0
335

In [56]:
for index, row in df.iterrows():

  if row['disp'] > 450:
    print(row)

mpg      10.40
cyl       8.00
disp    472.00
hp      205.00
drat      2.93
wt        5.25
qsec     17.98
vs        0.00
am        0.00
gear      3.00
carb      4.00
Name: Cadillac Fleetwood, dtype: float64
mpg      10.400
cyl       8.000
disp    460.000
hp      215.000
drat      3.000
wt        5.424
qsec     17.820
vs        0.000
am        0.000
gear      3.000
carb      4.000
Name: Lincoln Continental, dtype: float64

# Ordenação

In [57]:
df.sort_index(axis=1,ascending=False).head()

,wt,vs,qsec,mpg,hp,gear,drat,disp,cyl,carb,am
,,,,,,,,,,,
Mazda RX4,2.620,0,16.46,21.0,110,4,3.90,160.0,6,4,1
Mazda RX4 Wag,2.875,0,17.02,21.0,110,4,3.90,160.0,6,4,1
Datsun 710,2.320,1,18.61,22.8,93,4,3.85,108.0,4,1,1
Hornet 4 Drive,3.215,1,19.44,21.4,110,3,3.08,258.0,6,1,0
Hornet Sportabout,3.440,0,17.02,18.7,175,3,3.15,360.0,8,2,0

In [58]:
df.sort_values(by='mpg',ascending=False).head()

                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb

Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1     4     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1     4     1
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1     5     2
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1     4     2
Fiat X1-9       27.3    4  79.0   66  4.08  1.935  18.90   1   1     4     1

# Classificação

In [61]:
dfex = pd.DataFrame({'Pontos': [10, 20, 20, 30]})
dfex['Rank'] = dfex['Pontos'].rank(ascending=False)
print(dfex)

   Pontos  Rank
0      10   4.0
1      20   2.5
2      20   2.5
3      30   1.0

In [62]:
dfex = pd.DataFrame({'Pontos1': [10, 20, 20, 30],'Pontos2': [3, 2, 2, 1]})
dfex[['Rank1','Rank2']] = dfex.rank(method='first',ascending=False)
print(dfex)

   Pontos1  Pontos2  Rank1  Rank2
0       10        3    4.0    1.0
1       20        2    2.0    2.0
2       20        2    3.0    3.0
3       30        1    1.0    4.0