<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/hands_on_groupBy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Groupby**

In [1]:
import pandas as pd

df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/MASS/Cars93.csv',index_col=0)
df.index.name = ''
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
,,,,,,,,,,,,,,,,,,,,,
1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

# Group by simples

In [2]:
df.groupby('Type').Price.mean()

Type
Compact    18.212500
Large      24.300000
Midsize    27.218182
Small      10.166667
Sporty     19.392857
Van        19.100000
Name: Price, dtype: float64

In [17]:
df.groupby('Type')

In [4]:
df.groupby('Type')[['Price','MPG.city']].mean()

             Price   MPG.city
Type
Compact  18.212500  22.687500
Large    24.300000  18.363636
Midsize  27.218182  19.545455
Small    10.166667  29.857143
Sporty   19.392857  21.785714
Van      19.100000  17.000000

In [5]:
df.groupby(['Type','DriveTrain'])[['Price','MPG.city']].mean()

                        Price   MPG.city
Type    DriveTrain
Compact 4WD         19.500000  23.000000
        Front       16.715385  23.000000
        Rear        27.300000  20.500000
Large   Front       23.971429  19.000000
        Rear        24.875000  17.250000
Midsize Front       24.052941  19.705882
        Rear        37.980000  19.000000
Small   4WD          9.650000  29.000000
        Front       10.221053  29.947368
Sporty  4WD         20.100000  20.500000
        Front       16.014286  24.285714
        Rear        23.840000  18.800000
Van     4WD         19.460000  16.600000
        Front       18.650000  17.500000

Isso é um dataframe, mas cuidado com os índices compostos.

In [6]:
df.groupby(['Type','DriveTrain'])[['Price','MPG.city']].mean().reset_index()

       Type DriveTrain      Price   MPG.city
0   Compact        4WD  19.500000  23.000000
1   Compact      Front  16.715385  23.000000
2   Compact       Rear  27.300000  20.500000
3     Large      Front  23.971429  19.000000
4     Large       Rear  24.875000  17.250000
5   Midsize      Front  24.052941  19.705882
6   Midsize       Rear  37.980000  19.000000
7     Small        4WD   9.650000  29.000000
8     Small      Front  10.221053  29.947368
9    Sporty        4WD  20.100000  20.500000
10   Sporty      Front  16.014286  24.285714
11   Sporty       Rear  23.840000  18.800000
12      Van        4WD  19.460000  16.600000
13      Van      Front  18.650000  17.500000

In [7]:
df.groupby('Type').Price.agg(['mean','std'])

              mean        std
Type
Compact  18.212500   6.686890
Large    24.300000   6.337507
Midsize  27.218182  12.264841
Small    10.166667   1.953288
Sporty   19.392857   7.974716
Van      19.100000   1.878164

In [8]:
df_group = df.groupby(['Type','DriveTrain'])[['Price','MPG.city']].agg({ 'Price': ['mean', 'std'], 'MPG.city': 'max' })

print(type(df_group))
df_group

<class 'pandas.core.frame.DataFrame'>

                        Price            MPG.city
                         mean        std      max
Type    DriveTrain
Compact 4WD         19.500000        NaN       23
        Front       16.715385   6.003033       26
        Rear        27.300000   6.505382       21
Large   Front       23.971429   6.048061       20
        Rear        24.875000   7.747849       18
Midsize Front       24.052941   8.422004       23
        Rear        37.980000  17.851246       22
Small   4WD          9.650000   1.767767       33
        Front       10.221053   2.008200       46
Sporty  4WD         20.100000   8.061017       23
        Front       16.014286   4.643070       30
        Rear        23.840000  10.637575       22
Van     4WD         19.460000   2.191575       18
        Front       18.650000   1.586401       18

In [9]:
df_group.reset_index()

       Type DriveTrain      Price            MPG.city
                             mean        std      max
0   Compact        4WD  19.500000        NaN       23
1   Compact      Front  16.715385   6.003033       26
2   Compact       Rear  27.300000   6.505382       21
3     Large      Front  23.971429   6.048061       20
4     Large       Rear  24.875000   7.747849       18
5   Midsize      Front  24.052941   8.422004       23
6   Midsize       Rear  37.980000  17.851246       22
7     Small        4WD   9.650000   1.767767       33
8     Small      Front  10.221053   2.008200       46
9    Sporty        4WD  20.100000   8.061017       23
10   Sporty      Front  16.014286   4.643070       30
11   Sporty       Rear  23.840000  10.637575       22
12      Van        4WD  19.460000   2.191575       18
13      Van      Front  18.650000   1.586401       18

In [18]:
df_group.columns

Index(['Price_mean', 'Price_std', 'MPG.city_max'], dtype='object')

In [11]:
df_group

                        Price            MPG.city
                         mean        std      max
Type    DriveTrain
Compact 4WD         19.500000        NaN       23
        Front       16.715385   6.003033       26
        Rear        27.300000   6.505382       21
Large   Front       23.971429   6.048061       20
        Rear        24.875000   7.747849       18
Midsize Front       24.052941   8.422004       23
        Rear        37.980000  17.851246       22
Small   4WD          9.650000   1.767767       33
        Front       10.221053   2.008200       46
Sporty  4WD         20.100000   8.061017       23
        Front       16.014286   4.643070       30
        Rear        23.840000  10.637575       22
Van     4WD         19.460000   2.191575       18
        Front       18.650000   1.586401       18

In [12]:
df_group.unstack()

            Price                                                   MPG.city  \
             mean                          std                           max
DriveTrain    4WD      Front    Rear       4WD     Front       Rear      4WD
Type
Compact     19.50  16.715385  27.300       NaN  6.003033   6.505382     23.0
Large         NaN  23.971429  24.875       NaN  6.048061   7.747849      NaN
Midsize       NaN  24.052941  37.980       NaN  8.422004  17.851246      NaN
Small        9.65  10.221053     NaN  1.767767  2.008200        NaN     33.0
Sporty      20.10  16.014286  23.840  8.061017  4.643070  10.637575     23.0
Van         19.46  18.650000     NaN  2.191575  1.586401        NaN     18.0



DriveTrain Front  Rear
Type
Compact     26.0  21.0
Large       20.0  18.0
Midsize     23.0  22.0
Small       46.0   NaN
Sporty      30.0  22.0
Van         18.0   NaN

In [13]:
'_'.join(['a','b','c'])

'a_b_c'

In [14]:
df_group = df.groupby(['Type','DriveTrain'])[['Price','MPG.city']].agg({ 'Price': ['mean', 'std'], 'MPG.city': 'max' })

df_group.columns = ['_'.join(col).strip() for col in df_group.columns.values]
df_group

                    Price_mean  Price_std  MPG.city_max
Type    DriveTrain
Compact 4WD          19.500000        NaN            23
        Front        16.715385   6.003033            26
        Rear         27.300000   6.505382            21
Large   Front        23.971429   6.048061            20
        Rear         24.875000   7.747849            18
Midsize Front        24.052941   8.422004            23
        Rear         37.980000  17.851246            22
Small   4WD           9.650000   1.767767            33
        Front        10.221053   2.008200            46
Sporty  4WD          20.100000   8.061017            23
        Front        16.014286   4.643070            30
        Rear         23.840000  10.637575            22
Van     4WD          19.460000   2.191575            18
        Front        18.650000   1.586401            18

In [19]:
df_group.columns

Index(['Price_mean', 'Price_std', 'MPG.city_max'], dtype='object')

In [16]:
df_group.droplevel(0, axis=1).columns
df_group.droplevel(0, axis=1)

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

In [20]:
df_group.stack()

Type     DriveTrain
Compact  4WD         Price_mean      19.500000
                     MPG.city_max    23.000000
         Front       Price_mean      16.715385
                     Price_std        6.003033
                     MPG.city_max    26.000000
         Rear        Price_mean      27.300000
                     Price_std        6.505382
                     MPG.city_max    21.000000
Large    Front       Price_mean      23.971429
                     Price_std        6.048061
                     MPG.city_max    20.000000
         Rear        Price_mean      24.875000
                     Price_std        7.747849
                     MPG.city_max    18.000000
Midsize  Front       Price_mean      24.052941
                     Price_std        8.422004
                     MPG.city_max    23.000000
         Rear        Price_mean      37.980000
                     Price_std       17.851246
                     MPG.city_max    22.000000
Small    4WD         Price_mean       9.650000
                     Price_std        1.767767
                     MPG.city_max    33.000000
         Front       Price_mean      10.221053
                     Price_std        2.008200
                     MPG.city_max    46.000000
Sporty   4WD         Price_mean      20.100000
                     Price_std        8.061017
                     MPG.city_max    23.000000
         Front       Price_mean      16.014286
                     Price_std        4.643070
                     MPG.city_max    30.000000
         Rear        Price_mean      23.840000
                     Price_std       10.637575
                     MPG.city_max    22.000000
Van      4WD         Price_mean      19.460000
                     Price_std        2.191575
                     MPG.city_max    18.000000
         Front       Price_mean      18.650000
                     Price_std        1.586401
                     MPG.city_max    18.000000
dtype: float64

# Estrutura interna

In [21]:
G = df.groupby('Type')

In [22]:
G.keys

'Type'

In [23]:
for k in G.groups.keys():
    print (k)

Compact
Large
Midsize
Small
Sporty
Van

In [24]:
for k in G.groups.items():
    print (k)

('Compact', Index([3, 12, 13, 21, 25, 33, 43, 55, 58, 65, 68, 74, 78, 82, 90, 92], dtype='int64', name=''))
('Large', Index([7, 8, 10, 18, 20, 22, 30, 38, 52, 71, 77], dtype='int64', name=''))
('Midsize', Index([ 2,  4,  5,  6,  9, 11, 15, 27, 37, 47, 48, 49, 50, 51, 59, 61, 63, 67,
       69, 76, 86, 93],
      dtype='int64', name=''))
('Small', Index([ 1, 23, 24, 29, 31, 32, 39, 42, 44, 45, 53, 54, 62, 64, 73, 79, 80, 81,
       83, 84, 88],
      dtype='int64', name=''))
('Sporty', Index([14, 19, 28, 34, 35, 40, 41, 46, 57, 60, 72, 75, 85, 91], dtype='int64', name=''))
('Van', Index([16, 17, 26, 36, 56, 66, 70, 87, 89], dtype='int64', name=''))

In [25]:
G = df.groupby('Type')[['Price','MPG.city']].mean()

G

             Price   MPG.city
Type
Compact  18.212500  22.687500
Large    24.300000  18.363636
Midsize  27.218182  19.545455
Small    10.166667  29.857143
Sporty   19.392857  21.785714
Van      19.100000  17.000000

In [26]:
G = df.groupby('Type')[['Price','MPG.city']]

In [27]:
for k,v in G.groups.items():
    print(k,v)
    print(df.loc[v])
    print()

Compact Index([3, 12, 13, 21, 25, 33, 43, 55, 58, 65, 68, 74, 78, 82, 90, 92], dtype='int64', name='')
     Manufacturer     Model     Type  Min.Price  Price  Max.Price  MPG.city  \

3            Audi        90  Compact       25.9   29.1       32.3        20
12      Chevrolet  Cavalier  Compact        8.5   13.4       18.3        25
13      Chevrolet   Corsica  Compact       11.4   11.4       11.4        25
21       Chrysler   LeBaron  Compact       14.5   15.8       17.1        23
25          Dodge    Spirit  Compact       11.9   13.3       14.7        22
33           Ford     Tempo  Compact       10.4   11.3       12.2        22
43          Honda    Accord  Compact       13.8   17.5       21.2        24
55          Mazda       626  Compact       14.3   16.5       18.7        26
58  Mercedes-Benz      190E  Compact       29.0   31.9       34.9        20
65         Nissan    Altima  Compact       13.0   15.7       18.3        24
68     Oldsmobile   Achieva  Compact       13.0   13.5       14.0        24
74        Pontiac   Sunbird  Compact        9.4   11.1       12.8        23
78           Saab       900  Compact       20.3   28.7       37.1        20
82         Subaru    Legacy  Compact       16.3   19.5       22.7        23
90     Volkswagen    Passat  Compact       17.6   20.0       22.4        21
92          Volvo       240  Compact       21.8   22.7       23.5        21

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
3            26         Driver only      Front  ...          5     180
12           36                 NaN      Front  ...          5     182
13           34         Driver only      Front  ...          5     184
21           28  Driver & Passenger      Front  ...          6     183
25           27         Driver only      Front  ...          6     181
33           27                 NaN      Front  ...          5     177
43           31  Driver & Passenger      Front  ...          4     185
55           34         Driver only      Front  ...          5     184
58           29         Driver only       Rear  ...          5     175
65           30         Driver only      Front  ...          5     181
68           31                 NaN      Front  ...          5     188
74           31                 NaN      Front  ...          5     181
78           26         Driver only      Front  ...          5     184
82           30         Driver only        4WD  ...          5     179
90           30                 NaN      Front  ...          5     180
92           28         Driver only       Rear  ...          5     190

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

3         102     67           37           28.0          14.0    3375
12        101     66           38           25.0          13.0    2490
13        103     68           39           26.0          14.0    2785
21        104     68           41           30.5          14.0    3085
25        104     68           39           30.5          14.0    2970
33        100     68           39           27.5          13.0    2690
43        107     67           41           28.0          14.0    3040
55        103     69           40           29.5          14.0    2970
58        105     67           34           26.0          12.0    2920
65        103     67           40           28.5          14.0    3050
68        103     67           39           28.0          14.0    2910
74        101     66           39           25.0          13.0    2575
78         99     67           37           26.5          14.0    2775
82        102     67           37           27.0          14.0    3085
90        103     67           35           31.5          14.0    2985
92        104     67           37           29.5          14.0    2985

     Origin                Make

3   non-USA             Audi 90
12      USA  Chevrolet Cavalier
13      USA   Chevrolet Corsica
21      USA    Chrysler LeBaron
25      USA        Dodge Spirit
33      USA          Ford Tempo
43  non-USA        Honda Accord
55  non-USA           Mazda 626
58  non-USA  Mercedes-Benz 190E
65  non-USA       Nissan Altima
68      USA  Oldsmobile Achieva
74      USA     Pontiac Sunbird
78  non-USA            Saab 900
82  non-USA       Subaru Legacy
90  non-USA   Volkswagen Passat
92  non-USA           Volvo 240

[16 rows x 27 columns]

Large Index([7, 8, 10, 18, 20, 22, 30, 38, 52, 71, 77], dtype='int64', name='')
   Manufacturer           Model   Type  Min.Price  Price  Max.Price  MPG.city  \

7         Buick         LeSabre  Large       19.9   20.8       21.7        19
8         Buick      Roadmaster  Large       22.6   23.7       24.9        16
10     Cadillac         DeVille  Large       33.0   34.7       36.3        16
18    Chevrolet         Caprice  Large       18.0   18.8       19.6        17
20     Chrylser        Concorde  Large       18.4   18.4       18.4        20
22     Chrysler        Imperial  Large       29.5   29.5       29.5        20
30        Eagle          Vision  Large       17.5   19.3       21.2        20
38         Ford  Crown_Victoria  Large       20.1   20.9       21.7        18
52      Lincoln        Town_Car  Large       34.4   36.1       37.8        18
71   Oldsmobile    Eighty-Eight  Large       19.5   20.7       21.9        19
77      Pontiac      Bonneville  Large       19.4   24.4       29.4        19

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
7            28         Driver only      Front  ...          6     200
8            25         Driver only       Rear  ...          6     216
10           25         Driver only      Front  ...          6     206
18           26         Driver only       Rear  ...          6     214
20           28  Driver & Passenger      Front  ...          6     203
22           26         Driver only      Front  ...          6     203
30           28  Driver & Passenger      Front  ...          6     202
38           26         Driver only       Rear  ...          6     212
52           26  Driver & Passenger       Rear  ...          6     219
71           28         Driver only      Front  ...          6     201
77           28  Driver & Passenger      Front  ...          6     177

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

7         111     74           42           30.5          17.0    3470
8         116     78           45           30.5          21.0    4105
10        114     73           43           35.0          18.0    3620
18        116     77           42           29.5          20.0    3910
20        113     74           40           31.0          15.0    3515
22        110     69           44           36.0          17.0    3570
30        113     74           40           30.0          15.0    3490
38        114     78           43           30.0          21.0    3950
52        117     77           45           31.5          22.0    4055
71        111     74           42           31.5          17.0    3470
77        111     74           43           30.5          18.0    3495

    Origin                     Make

7      USA            Buick LeSabre
8      USA         Buick Roadmaster
10     USA         Cadillac DeVille
18     USA        Chevrolet Caprice
20     USA        Chrylser Concorde
22     USA        Chrysler Imperial
30     USA             Eagle Vision
38     USA      Ford Crown_Victoria
52     USA         Lincoln Town_Car
71     USA  Oldsmobile Eighty-Eight
77     USA       Pontiac Bonneville

[11 rows x 27 columns]

Midsize Index([ 2,  4,  5,  6,  9, 11, 15, 27, 37, 47, 48, 49, 50, 51, 59, 61, 63, 67,
       69, 76, 86, 93],
      dtype='int64', name='')
     Manufacturer          Model     Type  Min.Price  Price  Max.Price  \

2           Acura         Legend  Midsize       29.2   33.9       38.7
4            Audi            100  Midsize       30.8   37.7       44.6
5             BMW           535i  Midsize       23.7   30.0       36.2
6           Buick        Century  Midsize       14.2   15.7       17.3
9           Buick        Riviera  Midsize       26.3   26.3       26.3
11       Cadillac        Seville  Midsize       37.5   40.1       42.7
15      Chevrolet         Lumina  Midsize       13.4   15.9       18.4
27          Dodge        Dynasty  Midsize       14.8   15.6       16.4
37           Ford         Taurus  Midsize       15.6   20.2       24.8
47        Hyundai         Sonata  Midsize       12.4   13.9       15.3
48       Infiniti            Q45  Midsize       45.4   47.9       50.4
49          Lexus          ES300  Midsize       27.5   28.0       28.4
50          Lexus          SC300  Midsize       34.7   35.2       35.6
51        Lincoln    Continental  Midsize       33.3   34.3       35.3
59  Mercedes-Benz           300E  Midsize       43.8   61.9       80.0
61        Mercury         Cougar  Midsize       14.9   14.9       14.9
63     Mitsubishi       Diamante  Midsize       22.4   26.1       29.9
67         Nissan         Maxima  Midsize       21.0   21.5       22.0
69     Oldsmobile  Cutlass_Ciera  Midsize       14.2   16.3       18.4
76        Pontiac     Grand_Prix  Midsize       15.4   18.5       21.6
86         Toyota          Camry  Midsize       15.2   18.2       21.2
93          Volvo            850  Midsize       24.8   26.7       28.5

    MPG.city  MPG.highway             AirBags DriveTrain  ... Passengers  \
                                                          ...
2         18           25  Driver & Passenger      Front  ...          5
4         19           26  Driver & Passenger      Front  ...          6
5         22           30         Driver only       Rear  ...          4
6         22           31         Driver only      Front  ...          6
9         19           27         Driver only      Front  ...          5
11        16           25  Driver & Passenger      Front  ...          5
15        21           29                 NaN      Front  ...          6
27        21           27         Driver only      Front  ...          6
37        21           30         Driver only      Front  ...          5
47        20           27                 NaN      Front  ...          5
48        17           22         Driver only       Rear  ...          5
49        18           24         Driver only      Front  ...          5
50        18           23  Driver & Passenger       Rear  ...          4
51        17           26  Driver & Passenger      Front  ...          6
59        19           25  Driver & Passenger       Rear  ...          5
61        19           26                 NaN       Rear  ...          5
63        18           24         Driver only      Front  ...          5
67        21           26         Driver only      Front  ...          5
69        23           31         Driver only      Front  ...          5
76        19           27                 NaN      Front  ...          5
86        22           29         Driver only      Front  ...          5
93        20           28  Driver & Passenger      Front  ...          5

    Length  Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  \

2      195        115     71           38           30.0          15.0
4      193        106     70           37           31.0          17.0
5      186        109     69           39           27.0          13.0
6      189        105     69           41           28.0          16.0
9      198        108     73           41           26.5          14.0
11     204        111     74           44           31.0          14.0
15     198        108     71           40           28.5          16.0
27     192        105     69           42           30.5          16.0
37     192        106     71           40           27.5          18.0
47     184        104     69           41           31.0          14.0
48     200        113     72           42           29.0          15.0
49     188        103     70           40           27.5          14.0
50     191        106     71           39           25.0           9.0
51     205        109     73           42           30.0          19.0
59     187        110     69           37           27.0          15.0
61     199        113     73           38           28.0          15.0
63     190        107     70           43           27.5          14.0
67     188        104     69           41           28.5          14.0
69     190        105     70           42           28.0          16.0
76     195        108     72           41           28.5          16.0
86     188        103     70           38           28.5          15.0
93     184        105     69           38           30.0          15.0

    Weight   Origin                      Make

2     3560  non-USA              Acura Legend
4     3405  non-USA                  Audi 100
5     3640  non-USA                  BMW 535i
6     2880      USA             Buick Century
9     3495      USA             Buick Riviera
11    3935      USA          Cadillac Seville
15    3195      USA          Chevrolet Lumina
27    3080      USA             Dodge Dynasty
37    3325      USA               Ford Taurus
47    2885  non-USA            Hyundai Sonata
48    4000  non-USA              Infiniti Q45
49    3510  non-USA               Lexus ES300
50    3515  non-USA               Lexus SC300
51    3695      USA       Lincoln Continental
59    3525  non-USA        Mercedes-Benz 300E
61    3610      USA            Mercury Cougar
63    3730  non-USA       Mitsubishi Diamante
67    3200  non-USA             Nissan Maxima
69    2890      USA  Oldsmobile Cutlass_Ciera
76    3450      USA        Pontiac Grand_Prix
86    3030  non-USA              Toyota Camry
93    3245  non-USA                 Volvo 850

[22 rows x 27 columns]

Small Index([ 1, 23, 24, 29, 31, 32, 39, 42, 44, 45, 53, 54, 62, 64, 73, 79, 80, 81,
       83, 84, 88],
      dtype='int64', name='')
   Manufacturer    Model   Type  Min.Price  Price  Max.Price  MPG.city  \

1         Acura  Integra  Small       12.9   15.9       18.8        25
23        Dodge     Colt  Small        7.9    9.2       10.6        29
24        Dodge   Shadow  Small        8.4   11.3       14.2        23
29        Eagle   Summit  Small        7.9   12.2       16.5        29
31         Ford  Festiva  Small        6.9    7.4        7.9        31
32         Ford   Escort  Small        8.4   10.1       11.9        23
39          Geo    Metro  Small        6.7    8.4       10.0        46
42        Honda    Civic  Small        8.4   12.1       15.8        42
44      Hyundai    Excel  Small        6.8    8.0        9.2        29
45      Hyundai  Elantra  Small        9.0   10.0       11.0        22
53        Mazda      323  Small        7.4    8.3        9.1        29
54        Mazda  Protege  Small       10.9   11.6       12.3        28
62   Mitsubishi   Mirage  Small        7.7   10.3       12.9        29
64       Nissan   Sentra  Small        8.7   11.8       14.9        29
73      Pontiac   LeMans  Small        8.2    9.0        9.9        31
79       Saturn       SL  Small        9.2   11.1       12.9        28
80       Subaru    Justy  Small        7.3    8.4        9.5        33
81       Subaru   Loyale  Small       10.5   10.9       11.3        25
83       Suzuki    Swift  Small        7.3    8.6       10.0        39
84       Toyota   Tercel  Small        7.8    9.8       11.8        32
88   Volkswagen      Fox  Small        8.7    9.1        9.5        25

    MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
                                         ...
1            31          NaN      Front  ...          5     177        102
23           33          NaN      Front  ...          5     174         98
24           29  Driver only      Front  ...          5     172         97
29           33          NaN      Front  ...          5     174         98
31           33          NaN      Front  ...          4     141         90
32           30          NaN      Front  ...          5     171         98
39           50          NaN      Front  ...          4     151         93
42           46  Driver only      Front  ...          4     173        103
44           33          NaN      Front  ...          5     168         94
45           29          NaN      Front  ...          5     172         98
53           37          NaN      Front  ...          4     164         97
54           36          NaN      Front  ...          5     172         98
62           33          NaN      Front  ...          5     172         98
64           33  Driver only      Front  ...          5     170         96
73           41          NaN      Front  ...          4     177         99
79           38  Driver only      Front  ...          5     176        102
80           37          NaN        4WD  ...          4     146         90
81           30          NaN        4WD  ...          5     175         97
83           43          NaN      Front  ...          4     161         93
84           37  Driver only      Front  ...          5     162         94
88           33          NaN      Front  ...          4     163         93

    Width  Turn.circle Rear.seat.room  Luggage.room  Weight   Origin  \

1      68           37           26.5          11.0    2705  non-USA
23     66           32           26.5          11.0    2270      USA
24     67           38           26.5          13.0    2670      USA
29     66           36           26.5          11.0    2295      USA
31     63           33           26.0          12.0    1845      USA
32     67           36           28.0          12.0    2530      USA
39     63           34           27.5          10.0    1695  non-USA
42     67           36           28.0          12.0    2350  non-USA
44     63           35           26.0          11.0    2345  non-USA
45     66           36           28.0          12.0    2620  non-USA
53     66           34           27.0          16.0    2325  non-USA
54     66           36           26.5          13.0    2440  non-USA
62     67           36           26.0          11.0    2295  non-USA
64     66           33           26.0          12.0    2545  non-USA
73     66           35           25.5          17.0    2350      USA
79     68           40           26.5          12.0    2495      USA
80     60           32           23.5          10.0    2045  non-USA
81     65           35           27.5          15.0    2490  non-USA
83     63           34           27.5          10.0    1965  non-USA
84     65           36           24.0          11.0    2055  non-USA
88     63           34           26.0          10.0    2240  non-USA

                 Make

1       Acura Integra
23         Dodge Colt
24       Dodge Shadow
29       Eagle Summit
31       Ford Festiva
32        Ford Escort
39          Geo Metro
42        Honda Civic
44      Hyundai Excel
45    Hyundai Elantra
53          Mazda 323
54      Mazda Protege
62  Mitsubishi Mirage
64      Nissan Sentra
73     Pontiac LeMans
79          Saturn SL
80       Subaru Justy
81      Subaru Loyale
83       Suzuki Swift
84      Toyota Tercel
88     Volkswagen Fox

[21 rows x 27 columns]

Sporty Index([14, 19, 28, 34, 35, 40, 41, 46, 57, 60, 72, 75, 85, 91], dtype='int64', name='')
   Manufacturer     Model    Type  Min.Price  Price  Max.Price  MPG.city  \

14    Chevrolet    Camaro  Sporty       13.4   15.1       16.8        19
19    Chevrolet  Corvette  Sporty       34.6   38.0       41.5        17
28        Dodge   Stealth  Sporty       18.5   25.8       33.1        18
34         Ford   Mustang  Sporty       10.8   15.9       21.0        22
35         Ford     Probe  Sporty       12.8   14.0       15.2        24
40          Geo     Storm  Sporty       11.5   12.5       13.5        30

In [28]:
G = df.groupby(['Origin','Type'])[['Price','MPG.city']]

for k,v in G.groups.items():
    print(k,v)
    print(df.loc[v])
    print()

('USA', 'Compact') Index([12, 13, 21, 25, 33, 68, 74], dtype='int64', name='')
   Manufacturer     Model     Type  Min.Price  Price  Max.Price  MPG.city  \

12    Chevrolet  Cavalier  Compact        8.5   13.4       18.3        25
13    Chevrolet   Corsica  Compact       11.4   11.4       11.4        25
21     Chrysler   LeBaron  Compact       14.5   15.8       17.1        23
25        Dodge    Spirit  Compact       11.9   13.3       14.7        22
33         Ford     Tempo  Compact       10.4   11.3       12.2        22
68   Oldsmobile   Achieva  Compact       13.0   13.5       14.0        24
74      Pontiac   Sunbird  Compact        9.4   11.1       12.8        23

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
12           36                 NaN      Front  ...          5     182
13           34         Driver only      Front  ...          5     184
21           28  Driver & Passenger      Front  ...          6     183
25           27         Driver only      Front  ...          6     181
33           27                 NaN      Front  ...          5     177
68           31                 NaN      Front  ...          5     188
74           31                 NaN      Front  ...          5     181

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

12        101     66           38           25.0          13.0    2490
13        103     68           39           26.0          14.0    2785
21        104     68           41           30.5          14.0    3085
25        104     68           39           30.5          14.0    2970
33        100     68           39           27.5          13.0    2690
68        103     67           39           28.0          14.0    2910
74        101     66           39           25.0          13.0    2575

    Origin                Make

12     USA  Chevrolet Cavalier
13     USA   Chevrolet Corsica
21     USA    Chrysler LeBaron
25     USA        Dodge Spirit
33     USA          Ford Tempo
68     USA  Oldsmobile Achieva
74     USA     Pontiac Sunbird

[7 rows x 27 columns]

('USA', 'Large') Index([7, 8, 10, 18, 20, 22, 30, 38, 52, 71, 77], dtype='int64', name='')
   Manufacturer           Model   Type  Min.Price  Price  Max.Price  MPG.city  \

7         Buick         LeSabre  Large       19.9   20.8       21.7        19
8         Buick      Roadmaster  Large       22.6   23.7       24.9        16
10     Cadillac         DeVille  Large       33.0   34.7       36.3        16
18    Chevrolet         Caprice  Large       18.0   18.8       19.6        17
20     Chrylser        Concorde  Large       18.4   18.4       18.4        20
22     Chrysler        Imperial  Large       29.5   29.5       29.5        20
30        Eagle          Vision  Large       17.5   19.3       21.2        20
38         Ford  Crown_Victoria  Large       20.1   20.9       21.7        18
52      Lincoln        Town_Car  Large       34.4   36.1       37.8        18
71   Oldsmobile    Eighty-Eight  Large       19.5   20.7       21.9        19
77      Pontiac      Bonneville  Large       19.4   24.4       29.4        19

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
7            28         Driver only      Front  ...          6     200
8            25         Driver only       Rear  ...          6     216
10           25         Driver only      Front  ...          6     206
18           26         Driver only       Rear  ...          6     214
20           28  Driver & Passenger      Front  ...          6     203
22           26         Driver only      Front  ...          6     203
30           28  Driver & Passenger      Front  ...          6     202
38           26         Driver only       Rear  ...          6     212
52           26  Driver & Passenger       Rear  ...          6     219
71           28         Driver only      Front  ...          6     201
77           28  Driver & Passenger      Front  ...          6     177

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

7         111     74           42           30.5          17.0    3470
8         116     78           45           30.5          21.0    4105
10        114     73           43           35.0          18.0    3620
18        116     77           42           29.5          20.0    3910
20        113     74           40           31.0          15.0    3515
22        110     69           44           36.0          17.0    3570
30        113     74           40           30.0          15.0    3490
38        114     78           43           30.0          21.0    3950
52        117     77           45           31.5          22.0    4055
71        111     74           42           31.5          17.0    3470
77        111     74           43           30.5          18.0    3495

    Origin                     Make

7      USA            Buick LeSabre
8      USA         Buick Roadmaster
10     USA         Cadillac DeVille
18     USA        Chevrolet Caprice
20     USA        Chrylser Concorde
22     USA        Chrysler Imperial
30     USA             Eagle Vision
38     USA      Ford Crown_Victoria
52     USA         Lincoln Town_Car
71     USA  Oldsmobile Eighty-Eight
77     USA       Pontiac Bonneville

[11 rows x 27 columns]

('USA', 'Midsize') Index([6, 9, 11, 15, 27, 37, 51, 61, 69, 76], dtype='int64', name='')
   Manufacturer          Model     Type  Min.Price  Price  Max.Price  \

6         Buick        Century  Midsize       14.2   15.7       17.3
9         Buick        Riviera  Midsize       26.3   26.3       26.3
11     Cadillac        Seville  Midsize       37.5   40.1       42.7
15    Chevrolet         Lumina  Midsize       13.4   15.9       18.4
27        Dodge        Dynasty  Midsize       14.8   15.6       16.4
37         Ford         Taurus  Midsize       15.6   20.2       24.8
51      Lincoln    Continental  Midsize       33.3   34.3       35.3
61      Mercury         Cougar  Midsize       14.9   14.9       14.9
69   Oldsmobile  Cutlass_Ciera  Midsize       14.2   16.3       18.4
76      Pontiac     Grand_Prix  Midsize       15.4   18.5       21.6

    MPG.city  MPG.highway             AirBags DriveTrain  ... Passengers  \
                                                          ...
6         22           31         Driver only      Front  ...          6
9         19           27         Driver only      Front  ...          5
11        16           25  Driver & Passenger      Front  ...          5
15        21           29                 NaN      Front  ...          6
27        21           27         Driver only      Front  ...          6
37        21           30         Driver only      Front  ...          5
51        17           26  Driver & Passenger      Front  ...          6
61        19           26                 NaN       Rear  ...          5
69        23           31         Driver only      Front  ...          5
76        19           27                 NaN      Front  ...          5

    Length  Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  \

6      189        105     69           41           28.0          16.0
9      198        108     73           41           26.5          14.0
11     204        111     74           44           31.0          14.0
15     198        108     71           40           28.5          16.0
27     192        105     69           42           30.5          16.0
37     192        106     71           40           27.5          18.0
51     205        109     73           42           30.0          19.0
61     199        113     73           38           28.0          15.0
69     190        105     70           42           28.0          16.0
76     195        108     72           41           28.5          16.0

    Weight  Origin                      Make

6     2880     USA             Buick Century
9     3495     USA             Buick Riviera
11    3935     USA          Cadillac Seville
15    3195     USA          Chevrolet Lumina
27    3080     USA             Dodge Dynasty
37    3325     USA               Ford Taurus
51    3695     USA       Lincoln Continental
61    3610     USA            Mercury Cougar
69    2890     USA  Oldsmobile Cutlass_Ciera
76    3450     USA        Pontiac Grand_Prix

[10 rows x 27 columns]

('USA', 'Small') Index([23, 24, 29, 31, 32, 73, 79], dtype='int64', name='')
   Manufacturer    Model   Type  Min.Price  Price  Max.Price  MPG.city  \

23        Dodge     Colt  Small        7.9    9.2       10.6        29
24        Dodge   Shadow  Small        8.4   11.3       14.2        23
29        Eagle   Summit  Small        7.9   12.2       16.5        29
31         Ford  Festiva  Small        6.9    7.4        7.9        31
32         Ford   Escort  Small        8.4   10.1       11.9        23
73      Pontiac   LeMans  Small        8.2    9.0        9.9        31
79       Saturn       SL  Small        9.2   11.1       12.9        28

    MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
                                         ...
23           33          NaN      Front  ...          5     174         98
24           29  Driver only      Front  ...          5     172         97
29           33          NaN      Front  ...          5     174         98
31           33          NaN      Front  ...          4     141         90
32           30          NaN      Front  ...          5     171         98
73           41          NaN      Front  ...          4     177         99
79           38  Driver only      Front  ...          5     176        102

    Width  Turn.circle Rear.seat.room  Luggage.room  Weight  Origin  \

23     66           32           26.5          11.0    2270     USA
24     67           38           26.5          13.0    2670     USA
29     66           36           26.5          11.0    2295     USA
31     63           33           26.0          12.0    1845     USA
32     67           36           28.0          12.0    2530     USA
73     66           35           25.5          17.0    2350     USA
79     68           40           26.5          12.0    2495     USA

              Make

23      Dodge Colt
24    Dodge Shadow
29    Eagle Summit
31    Ford Festiva
32     Ford Escort
73  Pontiac LeMans
79       Saturn SL

[7 rows x 27 columns]

('USA', 'Sporty') Index([14, 19, 28, 34, 35, 60, 72, 75], dtype='int64', name='')
   Manufacturer     Model    Type  Min.Price  Price  Max.Price  MPG.city  \

14    Chevrolet    Camaro  Sporty       13.4   15.1       16.8        19
19    Chevrolet  Corvette  Sporty       34.6   38.0       41.5        17
28        Dodge   Stealth  Sporty       18.5   25.8       33.1        18
34         Ford   Mustang  Sporty       10.8   15.9       21.0        22
35         Ford     Probe  Sporty       12.8   14.0       15.2        24
60      Mercury     Capri  Sporty       13.3   14.1       15.0        23
72     Plymouth     Laser  Sporty       11.4   14.4       17.4        23
75      Pontiac  Firebird  Sporty       14.0   17.7       21.4        19

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
14           28  Driver & Passenger       Rear  ...          4     193
19           25         Driver only       Rear  ...          2     179
28           24         Driver only        4WD  ...          4     180
34           29         Driver only       Rear  ...          4     180
35           30         Driver only      Front  ...          4     179
60           26         Driver only      Front  ...          4     166
72           30                 NaN        4WD  ...          4     173
75           28  Driver & Passenger       Rear  ...          4     196

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

14        101     74           43           25.0          13.0    3240
19         96     74           43            NaN           NaN    3380
28         97     72           40           20.0          11.0    3805
34        101     68           40           24.0          12.0    2850
35        103     70           38           23.0          18.0    2710
60         95     65           36           19.0           6.0    2450
72         97     67           39           24.5           8.0    2640
75        101     75           43           25.0          13.0    3240

    Origin                Make

14     USA    Chevrolet Camaro
19     USA  Chevrolet Corvette
28     USA       Dodge Stealth
34     USA        Ford Mustang
35     USA          Ford Probe
60     USA       Mercury Capri
72     USA      Plymouth Laser
75     USA    Pontiac Firebird

[8 rows x 27 columns]

('USA', 'Van') Index([16, 17, 26, 36, 70], dtype='int64', name='')
   Manufacturer       Model Type  Min.Price  Price  Max.Price  MPG.city  \

16    Chevrolet  Lumina_APV  Van       14.7   16.3       18.0        18
17    Chevrolet       Astro  Van       14.7   16.6       18.6        15
26        Dodge     Caravan  Van       13.6   19.0       24.4        17
36         Ford    Aerostar  Van       14.5   19.9       25.3        15
70   Oldsmobile  Silhouette  Van       19.5   19.5       19.5        18

    MPG.highway      AirBags DriveTrain  ... Passengers  Length  Wheelbase  \
                                         ...
16           23          NaN      Front  ...          7     178        110
17           20          NaN        4WD  ...          8     194        111
26           21  Driver only        4WD  ...          7     175        112
36           20  Driver only        4WD  ...          7     176        119
70           23          NaN      Front  ...          7     194        110

    Width  Turn.circle Rear.seat.room  Luggage.room  Weight  Origin  \

16     74           44           30.5           NaN    3715     USA
17     78           42           33.5           NaN    4025     USA
26     72           42           26.5           NaN    3705     USA
36     72           45           30.0           NaN    3735     USA
70     74           44           30.5           NaN    3715     USA

                     Make

16   Chevrolet Lumina_APV
17        Chevrolet Astro
26          Dodge Caravan
36          Ford Aerostar
70  Oldsmobile Silhouette

[5 rows x 27 columns]

('non-USA', 'Compact') Index([3, 43, 55, 58, 65, 78, 82, 90, 92], dtype='int64', name='')
     Manufacturer   Model     Type  Min.Price  Price  Max.Price  MPG.city  \

3            Audi      90  Compact       25.9   29.1       32.3        20
43          Honda  Accord  Compact       13.8   17.5       21.2        24
55          Mazda     626  Compact       14.3   16.5       18.7        26
58  Mercedes-Benz    190E  Compact       29.0   31.9       34.9        20
65         Nissan  Altima  Compact       13.0   15.7       18.3        24
78           Saab     900  Compact       20.3   28.7       37.1        20
82         Subaru  Legacy  Compact       16.3   19.5       22.7        23
90     Volkswagen  Passat  Compact       17.6   20.0       22.4        21
92          Volvo     240  Compact       21.8   22.7       23.5        21

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
3            26         Driver only      Front  ...          5     180
43           31  Driver & Passenger      Front  ...          4     185
55           34         Driver only      Front  ...          5     184
58           29         Driver only       Rear  ...          5     175
65           30         Driver only      Front  ...          5     181
78           26         Driver only      Front  ...          5     184
82           30         Driver only        4WD  ...          5     179
90           30                 NaN      Front  ...          5     180
92           28         Driver only       Rear  ...          5     190

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

3         102     67           37           28.0          14.0    3375
43        107     67           41           28.0          14.0    3040
55        103     69           40           29.5          14.0    2970
58        105     67           34           26.0          12.0    2920
65        103     67           40           28.5          14.0    3050
78         99     67           37           26.5          14.0    2775
82        102     67           37           27.0          14.0    3085
90        103     67           35           31.5          14.0    2985
92        104     67           37           29.5          14.0    2985

     Origin                Make

3   non-USA             Audi 90
43  non-USA        Honda Accord
55  non-USA           Mazda 626
58  non-USA  Mercedes-Benz 190E
65  non-USA       Nissan Altima
78  non-USA            Saab 900
82  non-USA       Subaru Legacy
90  non-USA   Volkswagen Passat
92  non-USA           Volvo 240

[9 rows x 27 columns]

('non-USA', 'Midsize') Index([2, 4, 5, 47, 48, 49, 50, 59, 63, 67, 86, 93], dtype='int64', name='')
     Manufacturer     Model     Type  Min.Price  Price  Max.Price  MPG.city  \

2           Acura    Legend  Midsize       29.2   33.9       38.7        18
4            Audi       100  Midsize       30.8   37.7       44.6        19
5             BMW      535i  Midsize       23.7   30.0       36.2        22
47        Hyundai    Sonata  Midsize       12.4   13.9       15.3        20
48       Infiniti       Q45  Midsize       45.4   47.9       50.4        17
49          Lexus     ES300  Midsize       27.5   28.0       28.4        18
50          Lexus     SC300  Midsize       34.7   35.2       35.6        18
59  Mercedes-Benz      300E  Midsize       43.8   61.9       80.0        19
63     Mitsubishi  Diamante  Midsize       22.4   26.1       29.9        18
67         Nissan    Maxima  Midsize       21.0   21.5       22.0        21
86         Toyota     Camry  Midsize       15.2   18.2       21.2        22
93          Volvo       850  Midsize       24.8   26.7       28.5        20

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
                                                ...
2            25  Driver & Passenger      Front  ...          5     195
4            26  Driver & Passenger      Front  ...          6     193
5            30         Driver only       Rear  ...          4     186
47           27                 NaN      Front  ...          5     184
48           22         Driver only       Rear  ...          5     200
49           24         Driver only      Front  ...          5     188
50           23  Driver & Passenger       Rear  ...          4     191
59           25  Driver & Passenger       Rear  ...          5     187
63           24         Driver only      Front  ...          5     190
67           26         Driver only      Front  ...          5     188
86           29         Driver only      Front  ...          5     188
93           28  Driver & Passenger      Front  ...          5     184

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \

2         115     71           38           30.0          15.0    3560
4         106     70           37           31.0          17.0    3405
5         109     69           39           27.0          13.0    3640
47        104     69           41           31.0          14.0    2885
48        113     72           42           29.0          15.0    4000
49        103     70           40           27.5          14.0    3510
50        106     71           39           25.0           9.0    3515
59        110     69           37           27.0          15.0    3525
63        107     70           43           27.5          14.0    3730
67        104     69           41           28.5          14.0    3200

In [29]:
G = df.groupby('Type')[['Price','MPG.city']]

G.get_group('Large')

    Price  MPG.city

7    20.8        19
8    23.7        16
10   34.7        16
18   18.8        17
20   18.4        20
22   29.5        20
30   19.3        20
38   20.9        18
52   36.1        18
71   20.7        19
77   24.4        19

In [30]:
G = df.groupby(['Origin','Type'])[['Price','MPG.city']]

G.get_group(('USA','Large')) # Must be a tuple!!!

    Price  MPG.city

7    20.8        19
8    23.7        16
10   34.7        16
18   18.8        17
20   18.4        20
22   29.5        20
30   19.3        20
38   20.9        18
52   36.1        18
71   20.7        19
77   24.4        19

In [31]:
G = df.groupby(['Origin','Type'])[['Price','MPG.city']]

for k,v in G:
    print(k,v)
    print()

('USA', 'Compact')     Price  MPG.city

12   13.4        25
13   11.4        25
21   15.8        23
25   13.3        22
33   11.3        22
68   13.5        24
74   11.1        23

('USA', 'Large')     Price  MPG.city

7    20.8        19
8    23.7        16
10   34.7        16
18   18.8        17
20   18.4        20
22   29.5        20
30   19.3        20
38   20.9        18
52   36.1        18
71   20.7        19
77   24.4        19

('USA', 'Midsize')     Price  MPG.city

6    15.7        22
9    26.3        19
11   40.1        16
15   15.9        21
27   15.6        21
37   20.2        21
51   34.3        17
61   14.9        19
69   16.3        23
76   18.5        19

('USA', 'Small')     Price  MPG.city

23    9.2        29
24   11.3        23
29   12.2        29
31    7.4        31
32   10.1        23
73    9.0        31
79   11.1        28

('USA', 'Sporty')     Price  MPG.city

14   15.1        19
19   38.0        17
28   25.8        18
34   15.9        22
35   14.0        24
60   14.1        23
72   14.4        23
75   17.7        19

('USA', 'Van')     Price  MPG.city

16   16.3        18
17   16.6        15
26   19.0        17
36   19.9        15
70   19.5        18

('non-USA', 'Compact')     Price  MPG.city

3    29.1        20
43   17.5        24
55   16.5        26
58   31.9        20
65   15.7        24
78   28.7        20
82   19.5        23
90   20.0        21
92   22.7        21

('non-USA', 'Midsize')     Price  MPG.city

2    33.9        18
4    37.7        19
5    30.0        22
47   13.9        20
48   47.9        17
49   28.0        18
50   35.2        18
59   61.9        19
63   26.1        18
67   21.5        21
86   18.2        22
93   26.7        20

('non-USA', 'Small')     Price  MPG.city

1    15.9        25
39    8.4        46
42   12.1        42
44    8.0        29
45   10.0        22
53    8.3        29
54   11.6        28
62   10.3        29
64   11.8        29
80    8.4        33
81   10.9        25
83    8.6        39
84    9.8        32
88    9.1        25

('non-USA', 'Sporty')     Price  MPG.city

40   12.5        30
41   19.8        24
46   10.0        26
57   32.5        17
85   18.4        25
91   23.3        18

('non-USA', 'Van')     Price  MPG.city

56   19.1        18
66   19.1        17
87   22.7        18
89   19.7        17

# Agrupamento de valores numéricos

In [32]:
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
,,,,,,,,,,,,,,,,,,,,,
1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [33]:
df['Range_Price'] = pd.cut(df.Price, bins=3)

df[['Manufacturer','Model','Price','Range_Price']]

   Manufacturer    Model  Price       Range_Price

1         Acura  Integra   15.9   (7.346, 25.567]
2         Acura   Legend   33.9  (25.567, 43.733]
3          Audi       90   29.1  (25.567, 43.733]
4          Audi      100   37.7  (25.567, 43.733]
5           BMW     535i   30.0  (25.567, 43.733]
..          ...      ...    ...               ...
89   Volkswagen  Eurovan   19.7   (7.346, 25.567]
90   Volkswagen   Passat   20.0   (7.346, 25.567]
91   Volkswagen  Corrado   23.3   (7.346, 25.567]
92        Volvo      240   22.7   (7.346, 25.567]
93        Volvo      850   26.7  (25.567, 43.733]

[93 rows x 4 columns]

In [34]:
df.groupby('Range_Price').Price.count()

/tmp/ipykernel_725/2950890109.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Range_Price').Price.count()

Range_Price
(7.346, 25.567]     72
(25.567, 43.733]    19
(43.733, 61.9]       2
Name: Price, dtype: int64

In [44]:
df.dtypes

Manufacturer            object
Model                   object
Type                    object
Min.Price              float64
Price                  float64
Max.Price              float64
MPG.city                 int64
MPG.highway              int64
AirBags                 object
DriveTrain              object
Cylinders               object
EngineSize             float64
Horsepower               int64
RPM                      int64
Rev.per.mile             int64
Man.trans.avail         object
Fuel.tank.capacity     float64
Passengers               int64
Length                   int64
Wheelbase                int64
Width                    int64
Turn.circle              int64
Rear.seat.room         float64
Luggage.room           float64
Weight                   int64
Origin                  object
Make                    object
Range_Price           category
dtype: object

In [47]:
def map_price_range_to_name(price_range):
    if price_range == pd.Interval(7.346, 25.567, closed='right'):
        return 'Baixo'
    elif price_range == pd.Interval(25.567, 43.733, closed='right'):
        return 'Médio'
    elif price_range == pd.Interval(43.733, 61.9, closed='right'):
        return 'Alto'
    return None # Se houver alguma faixa não mapeada

df['Range_Price_name'] = df['Range_Price'].apply(map_price_range_to_name).astype(str)

display(df[['Price', 'Range_Price', 'Range_Price_name']].head())
display(df['Range_Price_name'].value_counts())

   Price       Range_Price Range_Price_name

1   15.9   (7.346, 25.567]            Baixo
2   33.9  (25.567, 43.733]            Médio
3   29.1  (25.567, 43.733]            Médio
4   37.7  (25.567, 43.733]            Médio
5   30.0  (25.567, 43.733]            Médio

Range_Price_name
Baixo    72
Médio    19
Alto      2
Name: count, dtype: int64

In [36]:
print(pd.__version__)

2.2.2

In [43]:
data = {'PatientID': [1, 2, 3, 4, 5],
        'BloodType': ['A', 'B', 'B', 'A', 'A']}
Blood = pd.DataFrame(data)

blood_categories = pd.CategoricalDtype(categories=['O', 'A', 'B', 'AB'], ordered=True)
Blood['BloodType'] = Blood['BloodType'].astype(blood_categories)

display(Blood)
display(Blood.groupby('BloodType').BloodType.count())
display(Blood.groupby('BloodType',observed=True).BloodType.count())

   PatientID BloodType
0          1         A
1          2         B
2          3         B
3          4         A
4          5         A

/tmp/ipykernel_725/3091165072.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  display(Blood.groupby('BloodType').BloodType.count())

BloodType
O     0
A     3
B     2
AB    0
Name: BloodType, dtype: int64

BloodType
A    3
B    2
Name: BloodType, dtype: int64