<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/IMT_regressao_scale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aprendizado Supervisionado e Regressão Linear `statsmodels`**

Neste laboratório:

1. Aplique os modelos de regressão linear com statsmodel
2. Entenda os efeitos da normalização
3. Avalie o uso de diferentes preditores e seu impacto sobre a variável objetivo

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import statsmodels.formula.api as sm

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Caso: **Estimando o preço de imóveis**

Empregue modelos de regressão simples e múltipla para estimar o preço dos imóveis.

In [ ]:
df = pd.read_excel('http://meusite.mackenzie.br/rogerio/data_load/regressao_preco_imoveis.xlsx')
df.head()

                bairro  areaM2  suites  dormitorios  banheiros  vagas    preco
0  vila-nova-conceicao      32       1            1          1      1   490000
1  vila-nova-conceicao     157       2            2          2      2  3180000
2  vila-nova-conceicao     205       2            3          3      3  1900000
3  vila-nova-conceicao     193       3            3          3      3  3565000
4  vila-nova-conceicao     116       1            3          2      2  1605000

## Exploração inicial dos dados

In [ ]:
df.describe()

,areaM2,suites,dormitorios,banheiros,vagas,preco
count,3741.000000,3741.000000,3741.000000,3741.000000,3741.000000,3.741000e+03
mean,140.343758,1.700882,2.946271,3.095429,2.225341,1.553746e+06
std,60.051791,0.994945,0.759292,1.372859,1.000940,1.073607e+06
min,20.000000,1.000000,1.000000,1.000000,1.000000,2.800000e+05
25%,94.000000,1.000000,3.000000,2.000000,1.000000,8.500000e+05
50%,130.000000,1.000000,3.000000,3.000000,2.000000,1.200000e+06
75%,180.000000,2.000000,3.000000,4.000000,3.000000,1.880000e+06
max,299.000000,6.000000,6.000000,9.000000,5.000000,8.000000e+06

In [ ]:
df.isnull().sum()

bairro         0
areaM2         0
suites         0
dormitorios    0
banheiros      0
vagas          0
preco          0
dtype: int64

In [ ]:
df = df.drop(columns='bairro')
df.head()

   areaM2  suites  dormitorios  banheiros  vagas    preco
0      32       1            1          1      1   490000
1     157       2            2          2      2  3180000
2     205       2            3          3      3  1900000
3     193       3            3          3      3  3565000
4     116       1            3          2      2  1605000

# Q1.

Considere somente os dados numéricos, sem transformações. Qual o R2 obtido da regressão linear para estimativa do preço dos imóveis?

# Q2.

Considere somente os dados numéricos, sem transformações. Quais atributos preditores são significativos?

# Q3.

Considere somente os dados numéricos, sem transformações. Qual o R2 obtido somente com os coeficientes significativos?

# Q4.

Considere somente os dados numéricos, sem transformações. Considerando somente os coeficientes significativos da regressão linear, qual o preço estimado de um imóvel de 134 m2, uma suite, 4 dormitórios e 2 vagas de garagem?

# Q5.

Podemos afirmar que o atributo que influencia mais o preço em termos absolutos é o número de dormitórios (Verdadeiro/Falso)?

# Scale 1

# Q6.

Normalize os dados, incluindo o preço, apenas dividindo pelo valor máximo de cada atributo e refaça a regressão linear somente os preditores significativos. Qual a estimativa do preço agora?

# Q7.

Qual atributo influencia mais no preço dos imóveis segundo seu modelo agora?

# Scale 2

# Q8.

Verifique que os mesmos resultados podem ser obtidos normalizando apenas as variáveis preditoras.

# Scale 3

# Q9.

Verifique agora o resultado de outros mecanismos de normalização como o `MinMaxScaler`, `StandardScaler`. Eles influenciam os resultados?

# Pressupostos e `scikit-learn`

# Q9.

Faça um gráfico dos dados para verificar os aspectos de outliers e homocedasticidade dos dados.

# Q10.

Construa o mesmo modelo, com os 4 preditores significativos, com o Scikit-learn - com e sem o intercept. Há diferença nos resultados do `statsmodels` e `scikit-learn`?

# Q11.

Faça o modelo sm.ols incluindo todas as variáveis preditoras, mesmo o bairro que é não numérico, e veja como a api se comporta para criar o modelo. Faça a previsão para o mesmo case considerando o bairro de `vila-mariana`. Observe as variáveis preditoras no summary do modelo. O que aconteceu?

# Q12.

Aplique agora, ao modelo anterior, o `np.Log()` do preço para reduzir a heterocedasticidade. Exclua ainda os parâmetros não significativos. O resultado é melhor? Altera o valor da predição?