<a href="https://colab.research.google.com/github/Rogerio-mack/IMT_CD_2026/blob/main/Pandas_indices_handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Índices, Localizadores `.loc` e `.iloc`**


## Sumário

* Seleções (`read-only`), empregue

>> `df[ row-selection-criteria ][ columns-selection-list ]`

>> Exemplos: **`df[ df.age < 16 ][['name','age']]`**

* Alterações (`update`) por chave (rótulo) do índice ou por posição, empregue

>> `df.loc[ rows-key, column-key (name) ]...`, ou

>> Exemplos: **`df.loc[ 'VW 60', 'mpg']`**

>> `df.iloc[ rows-position, column-position ]...`

>> Exemplos: **`df.iloc[ 5, 1:4 ]`**

* Alterações (`update`) com seleção de dados, empregue por chave (rótulo) do índice ou por posição, empregue

>> `df.loc[ row-selection-criteria, column-key (name) ]...`,  ou

>> `df.iloc[ row-selection-criteria.index, column-position ]...`

* Query

>> `df.query[ ' non-predix row-selection-criteria  ' ]`, como `df.query['blood="AB"']`

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv',index_col='rownames')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [4]:
df.shape

(32, 11)

# Índices

Índices de linha e coluna.

In [5]:
df.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [6]:
df.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object', name='')

In [7]:
print(df['mpg'])

Mazda RX4              21.0
Mazda RX4 Wag          21.0
Datsun 710             22.8
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Valiant                18.1
Duster 360             14.3
Merc 240D              24.4
Merc 230               22.8
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Cadillac Fleetwood     10.4
Lincoln Continental    10.4
Chrysler Imperial      14.7
Fiat 128               32.4
Honda Civic            30.4
Toyota Corolla         33.9
Toyota Corona          21.5
Dodge Challenger       15.5
AMC Javelin            15.2
Camaro Z28             13.3
Pontiac Firebird       19.2
Fiat X1-9              27.3
Porsche 914-2          26.0
Lotus Europa           30.4
Ford Pantera L         15.8
Ferrari Dino           19.7
Maserati Bora          15.0
Volvo 142E             21.4
Name: mpg, dtype: float64

## `set_index()` e `reset_index()`

In [8]:
df.reset_index()

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [9]:
# df.reset_index(inplace=True)

df = df.reset_index()
df.head()

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

### Observação sobre o in-place

In [10]:
df.drop(columns='cyl')
print('Coluna excluída... (?)')
df.head()

Coluna excluída... (?)

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.columns

Index(['', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [12]:
df.columns = ['car name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb']
df.head()

,car name,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [13]:
df = df.set_index('car name')
df.index.name = ''
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

#### Reset drop true

In [14]:
df2 = pd.read_csv('https://github.com/Rogerio-mack/IMT_CD_2026/raw/refs/heads/main/data/insurance.csv')
df2

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [16]:
df3 = df2[ df2.age > 62 ]

df3 = df3.reset_index(drop=True)
df3.head()

   age     sex     bmi  children smoker     region      charges
0   63  female  23.085         0     no  northeast  14451.83515
1   63    male  28.310         0     no  northwest  13770.09790
2   64    male  24.700         1     no  northwest  30166.61817
3   64  female  31.300         2    yes  southwest  47291.05500
4   63    male  35.090         0    yes  southeast  47055.53210

# `.loc`, `.iloc`

* `.loc`, por label (rótulo, chave)
* `.iloc`, por posição

In [17]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
,,,,,,,,,,,
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [18]:
df.loc['Datsun 710','mpg']

np.float64(22.8)

In [19]:
df.iloc[2,0]

np.float64(22.8)

In [ ]:
df.iloc[2:10,5:6]

                      wt

Datsun 710         2.320
Hornet 4 Drive     3.215
Hornet Sportabout  3.440
Valiant            3.460
Duster 360         3.570
Merc 240D          3.190
Merc 230           3.150
Merc 280           3.440

In [ ]:
df.iloc[2:10,5::]

                      wt   qsec  vs  am  gear  carb

Datsun 710         2.320  18.61   1   1     4     1
Hornet 4 Drive     3.215  19.44   1   0     3     1
Hornet Sportabout  3.440  17.02   0   0     3     2
Valiant            3.460  20.22   1   0     3     1
Duster 360         3.570  15.84   0   0     3     4
Merc 240D          3.190  20.00   1   0     4     2
Merc 230           3.150  22.90   1   0     4     2
Merc 280           3.440  18.30   1   0     4     4

In [ ]:
df.loc['Datsun 710':'Ford Pantera L', 'hp'::]

                      hp  drat     wt   qsec  vs  am  gear  carb

Datsun 710            93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive       110  3.08  3.215  19.44   1   0     3     1
Hornet Sportabout    175  3.15  3.440  17.02   0   0     3     2
Valiant              105  2.76  3.460  20.22   1   0     3     1
Duster 360           245  3.21  3.570  15.84   0   0     3     4
Merc 240D             62  3.69  3.190  20.00   1   0     4     2
Merc 230              95  3.92  3.150  22.90   1   0     4     2
Merc 280             123  3.92  3.440  18.30   1   0     4     4
Merc 280C            123  3.92  3.440  18.90   1   0     4     4
Merc 450SE           180  3.07  4.070  17.40   0   0     3     3
Merc 450SL           180  3.07  3.730  17.60   0   0     3     3
Merc 450SLC          180  3.07  3.780  18.00   0   0     3     3
Cadillac Fleetwood   205  2.93  5.250  17.98   0   0     3     4
Lincoln Continental  215  3.00  5.424  17.82   0   0     3     4
Chrysler Imperial    230  3.23  5.345  17.42   0   0     3     4
Fiat 128              66  4.08  2.200  19.47   1   1     4     1
Honda Civic           52  4.93  1.615  18.52   1   1     4     2
Toyota Corolla        65  4.22  1.835  19.90   1   1     4     1
Toyota Corona         97  3.70  2.465  20.01   1   0     3     1
Dodge Challenger     150  2.76  3.520  16.87   0   0     3     2
AMC Javelin          150  3.15  3.435  17.30   0   0     3     2
Camaro Z28           245  3.73  3.840  15.41   0   0     3     4
Pontiac Firebird     175  3.08  3.845  17.05   0   0     3     2
Fiat X1-9             66  4.08  1.935  18.90   1   1     4     1
Porsche 914-2         91  4.43  2.140  16.70   0   1     5     2
Lotus Europa         113  3.77  1.513  16.90   1   1     5     2
Ford Pantera L       264  4.22  3.170  14.50   0   1     5     4

## Cuidado com Rótulos numéricos

In [20]:
df = df.reset_index()
df.head()

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [23]:
%%script echo skipping
df.loc[0,1]

skipping

In [24]:
df.iloc[0,1]

np.float64(21.0)

In [ ]:
df.loc[0,'mpg']

np.float64(21.0)

#### **AQUI O PROBLEMA**

In [21]:
df.loc[0:3,'cyl':'disp']

   cyl   disp
0    6  160.0
1    6  160.0
2    4  108.0
3    6  258.0

In [25]:
df.head()

,,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2